// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Accessibility = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M16.209 8.051a1 1 0 0 1 .393 1.961l-3.282.765a.414.414 0 0 0-.32.402c0 .709.152 1.41.445 2.055l1.965 4.323a1 1 0 0 1-1.82.828l-1.407-3.096c-.079-.173-.119-.26-.183-.26-.064.001-.103.087-.182.26l-1.408 3.096a1 1 0 0 1-1.82-.828l1.965-4.322A5 5 0 0 0 11 11.178a.415.415 0 0 0-.317-.403L7.5 10.012a1 1 0 0 1 .393-1.96c1.399.327 2.099.49 2.805.57.866.097 1.74.099 2.607.007.706-.076 1.407-.235 2.807-.555zM11.992 4.714a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1c6.075 0 11 4.925 11 11s-4.925 11-11 11S1 18.075 1 12 5.925 1 12 1m0 2a9 9 0 1 0 0 18 9 9 0 0 0 0-18"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Accessibility };
