// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ArrowUpRight = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M17 6q.084 0 .165.015l.03.005.045.01.048.012q.075.023.145.058l.042.02A1 1 0 0 1 18 7v10a1 1 0 1 1-2 0V9.414l-8.293 8.293a1 1 0 1 1-1.414-1.414L14.586 8H7a1 1 0 0 1 0-2z"
    />
  </IconSvg>
);
export { ArrowUpRight };
