// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ArrowDownWideNarrow = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M6 4a1 1 0 0 1 2 0v13.586l2.293-2.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-1.414 0l-4-4a1 1 0 1 1 1.414-1.414L6 17.586zm9 7a1 1 0 1 1 0 2h-4a1 1 0 1 1 0-2zm3-4a1 1 0 1 1 0 2h-7a1 1 0 1 1 0-2zm3-4a1 1 0 1 1 0 2H11a1 1 0 1 1 0-2z"
    />
  </IconSvg>
);
export { ArrowDownWideNarrow };
