// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ArrowCornerDownRight = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M4 2a1 1 0 0 1 1 1v5.59a3 3 0 0 0 3 3h9.586l-3.293-3.293a1 1 0 1 1 1.414-1.414l5 5a1 1 0 0 1 .25.413l.015.062a1 1 0 0 1-.015.522 1 1 0 0 1-.173.329q-.035.046-.077.088l-5 5a1 1 0 1 1-1.414-1.414l3.293-3.293H8a5 5 0 0 1-5-5V3a1 1 0 0 1 1-1"
    />
  </IconSvg>
);
export { ArrowCornerDownRight };
