// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ArrowUpNarrowWide = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M6 20V6.414L3.707 8.707a1 1 0 1 1-1.414-1.414l4-4 .076-.068a1 1 0 0 1 1.338.068l4 4a1 1 0 1 1-1.414 1.414L8 6.414V20a1 1 0 1 1-2 0m15-1a1 1 0 1 1 0 2H11a1 1 0 1 1 0-2zm-3-4a1 1 0 1 1 0 2h-7a1 1 0 1 1 0-2zm-3-4a1 1 0 1 1 0 2h-4a1 1 0 1 1 0-2z"
    />
  </IconSvg>
);
export { ArrowUpNarrowWide };
