// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ArrowUpLeft = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M17 6a1 1 0 1 1 0 2H9.414l8.293 8.293a1 1 0 1 1-1.414 1.414L8 9.414V17a1 1 0 1 1-2 0V7a1 1 0 0 1 .165-.55c.09-.137.214-.251.36-.33l.041-.02a1 1 0 0 1 .141-.057l.062-.016.034-.007.006-.001.088-.014Q6.947 5.999 7 6z"
    />
  </IconSvg>
);
export { ArrowUpLeft };
