// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const BookmarkFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M15.626 1.876q1.351 0 2.046.704.694.703.694 2.063v15.93q0 .612-.32.96-.31.356-.85.356a1.13 1.13 0 0 1-.684-.229q-.31-.218-.905-.794l-3.534-3.49q-.073-.081-.155 0l-3.526 3.49q-.594.575-.914.794a1.12 1.12 0 0 1-.676.229q-.548 0-.868-.356-.31-.348-.31-.96V4.643q0-1.36.694-2.063.695-.704 2.046-.704z"
    />
  </IconSvg>
);
export { BookmarkFilled };
