// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Box = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1.002a3 3 0 0 1 1.495.4h.001l7 4 .004.002A3 3 0 0 1 22 8v8.002a3 3 0 0 1-1.5 2.595l-.004.003-7 4v-.001a3 3 0 0 1-1.389.396 1 1 0 0 1-.211 0 3 3 0 0 1-1.392-.396l-7-4-.004-.002A3 3 0 0 1 2 16V7.999l.007-.197A3 3 0 0 1 3.5 5.404l.004-.003 7-4c.455-.262.97-.4 1.496-.4M4 15.999l.009.13a1 1 0 0 0 .487.732L11 20.577v-7.999L4 8.556zm9-3.42v7.998l6.504-3.716A1 1 0 0 0 20 16V8.556zm-1-9.577a1 1 0 0 0-.5.134l-.004.002-6.475 3.698L12 10.846l6.978-4.01-6.473-3.698-.004-.002a1 1 0 0 0-.5-.134"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Box };
