// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Briefcase = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M14 1a3 3 0 0 1 3 3v1h3a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3h3V4a3 3 0 0 1 3-3zm3 18h3a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1h-3zm-8 0h6V7H9zM4 7a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h3V7zm6-4a1 1 0 0 0-1 1v1h6V4a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Briefcase };
