// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const BulletedList = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M3.01 18a1 1 0 1 1 0 2H3a1 1 0 1 1 0-2zM21 18a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2zM3.01 11a1 1 0 1 1 0 2H3a1 1 0 1 1 0-2zM21 11a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2zM3.01 4a1 1 0 0 1 0 2H3a1 1 0 0 1 0-2zM21 4a1 1 0 1 1 0 2H8a1 1 0 0 1 0-2z"
    />
  </IconSvg>
);
export { BulletedList };
