// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const CalendarClock = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M16 1a1 1 0 0 1 1 1v1h2a3 3 0 0 1 3 3v1.5a1 1 0 1 1-2 0V6a1 1 0 0 0-1-1h-2v1a1 1 0 1 1-2 0V5H9v1a1 1 0 0 1-2 0V5H5a1 1 0 0 0-1 1v3h4a1 1 0 1 1 0 2H4v9a1 1 0 0 0 1 1h3.5a1 1 0 1 1 0 2H5a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3h2V2a1 1 0 0 1 2 0v1h6V2a1 1 0 0 1 1-1"
    />
    <path
      fill="currentColor"
      d="M16 13a1 1 0 0 1 1 1v1.645l1.13.707a1.001 1.001 0 0 1-1.06 1.696l-1.6-1A1 1 0 0 1 15 16.2V14a1 1 0 0 1 1-1"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M16 9a7 7 0 1 1 0 14 7 7 0 0 1 0-14m0 2a5 5 0 1 0 0 10 5 5 0 0 0 0-10"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { CalendarClock };
