// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Calendar2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M8.01 17a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2zM12.01 17a1 1 0 1 1 0 2H12a1 1 0 1 1 0-2zM16.01 17a1 1 0 1 1 0 2H16a1 1 0 1 1 0-2zM8.01 13a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2zM12.01 13a1 1 0 1 1 0 2H12a1 1 0 1 1 0-2zM16.01 13a1 1 0 1 1 0 2H16a1 1 0 1 1 0-2z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M16 1a1 1 0 0 1 1 1v1h2a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3h2V2a1 1 0 0 1 2 0v1h6V2a1 1 0 0 1 1-1M4 20a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-9H4zM5 5a1 1 0 0 0-1 1v3h16V6a1 1 0 0 0-1-1h-2v1a1 1 0 1 1-2 0V5H9v1a1 1 0 0 1-2 0V5z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Calendar2 };
