// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Change = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M5.02 5.001q.027 0 .053.002l.053.005q.018.002.035.006a1 1 0 0 1 .546.279l3 3a1 1 0 0 1-1.414 1.414L6 8.414V16a1 1 0 0 0 1 1h6a1 1 0 1 1 0 2H7a3 3 0 0 1-3-3V8.414L2.707 9.707a1 1 0 0 1-1.414-1.414l3-3a1 1 0 0 1 .45-.259l.049-.013.033-.005A1 1 0 0 1 4.98 5L5 5zM17 5a3 3 0 0 1 3 3v7.586l1.293-1.293a1 1 0 0 1 1.414 1.414l-3 3a1 1 0 0 1-.416.25l-.05.012-.048.011-.021.003Q19.088 19 19 19l-.103-.005q-.032-.004-.063-.01l-.031-.005-.035-.008-.061-.016a1 1 0 0 1-.414-.249l-3-3a1 1 0 1 1 1.414-1.414L18 15.586V8a1 1 0 0 0-1-1h-6a1 1 0 1 1 0-2z"
    />
  </IconSvg>
);
export { Change };
