// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ChevronUp = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M11.37 8.225a1 1 0 0 1 1.337.068l6 6a1 1 0 1 1-1.414 1.414L12 10.414l-5.293 5.293a1 1 0 1 1-1.414-1.414l6-6z"
    />
  </IconSvg>
);
export { ChevronUp };
