// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const CircleCheckFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1c6.075 0 11 4.925 11 11s-4.925 11-11 11S1 18.075 1 12 5.925 1 12 1m4.078 8.022a1.1 1.1 0 0 0-1.556 0L10.9 12.645l-1.422-1.423a1.1 1.1 0 1 0-1.556 1.556l2.2 2.2a1.1 1.1 0 0 0 1.556 0l4.4-4.4a1.1 1.1 0 0 0 0-1.556"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { CircleCheckFilled };
