// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const CirclePause = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M21 12a9 9 0 1 0-18 0 9 9 0 0 0 18 0M9 15V9a1 1 0 0 1 2 0v6a1 1 0 1 1-2 0m4 0V9a1 1 0 1 1 2 0v6a1 1 0 1 1-2 0m10-3c0 6.075-4.925 11-11 11S1 18.075 1 12 5.925 1 12 1s11 4.925 11 11"
    />
  </IconSvg>
);
export { CirclePause };
