// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ClosedCaption = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M8.45 8.04a4 4 0 0 1 1.882.187 1 1 0 0 1-.663 1.886 2.004 2.004 0 0 0-2.44.968 2 2 0 0 0 2.44 2.806 1 1 0 0 1 .663 1.886A4.003 4.003 0 0 1 5.005 12 4 4 0 0 1 8.45 8.04M15.45 8.04a4 4 0 0 1 1.882.187 1 1 0 0 1-.663 1.886 2.004 2.004 0 0 0-2.44.968 2.001 2.001 0 0 0 2.44 2.806 1 1 0 0 1 .663 1.886A4.003 4.003 0 0 1 12.005 12a4 4 0 0 1 3.445-3.96"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M20 4a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3zM4 6a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { ClosedCaption };
