// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const CloudArrow = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12.02 12.001q.03 0 .06.002l.036.004.053.008.048.009q.024.005.048.013l.038.01a1 1 0 0 1 .404.246l4 4a1 1 0 0 1-1.414 1.414L13 15.414V21a1 1 0 0 1-2 0v-5.586l-2.293 2.293a1 1 0 0 1-1.414-1.414l4-4a1 1 0 0 1 .564-.283l.017-.002.058-.005.047-.002h.041"
    />
    <path
      fill="currentColor"
      d="M8.37 2.028a8 8 0 0 1 6.522 2.56A8 8 0 0 1 16.415 7H17.5a5.5 5.5 0 0 1 5.263 3.904 5.5 5.5 0 0 1-2.208 6.17 1 1 0 0 1-1.11-1.662A3.502 3.502 0 0 0 17.5 8.999h-1.79a1 1 0 0 1-.958-.713A6 6 0 1 0 4.715 14.2a1 1 0 0 1-1.43 1.398 8 8 0 0 1-2.213-6.647A8 8 0 0 1 8.37 2.028"
    />
  </IconSvg>
);
export { CloudArrow };
