// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Columns2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M19 2a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3zm-6 18h6a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1h-6zM5 4a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h6V4z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Columns2 };
