// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Columns3 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M19 2a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3zM5 4a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h3V4zm11 16h3a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1h-3zm-6 0h4V4h-4z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Columns3 };
