// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Compare = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M5 2a4 4 0 0 1 1 7.874V16a1 1 0 0 0 1 1h2.586l-1.293-1.293a1 1 0 1 1 1.414-1.414l3 3a1 1 0 0 1 .25.414l.015.062q.027.111.028.231 0 .12-.028.23l-.016.062a1 1 0 0 1-.165.317 1 1 0 0 1-.084.098l-3 3a1 1 0 1 1-1.414-1.414L9.586 19H7a3 3 0 0 1-3-3V9.874A4.002 4.002 0 0 1 5 2m0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4M14.293 2.293a1 1 0 1 1 1.414 1.414L14.414 5H17a3 3 0 0 1 3 3v6.126A4.002 4.002 0 0 1 19 22a4 4 0 0 1-1-7.874V8a1 1 0 0 0-1-1h-2.586l1.293 1.293a1 1 0 1 1-1.414 1.414l-3-3a1 1 0 0 1-.173-.232l-.02-.042a1 1 0 0 1-.057-.141l-.016-.062a1 1 0 0 1 0-.461l.016-.062a1 1 0 0 1 .122-.257q.056-.085.128-.157zM19 16a2 2 0 1 0 0 4 2 2 0 0 0 0-4"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Compare };
