// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Divider = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M19 15a1 1 0 0 1 1 1v3c0 .825-.403 1.567-.918 2.082S17.825 22 17 22H7c-.825 0-1.567-.403-2.082-.918S4 19.825 4 19v-3a1 1 0 1 1 2 0v3c0 .175.097.433.332.668S6.825 20 7 20h10c.175 0 .433-.097.668-.332S18 19.175 18 19v-3a1 1 0 0 1 1-1M20 11a1 1 0 1 1 0 2H4a1 1 0 1 1 0-2zM17 2c.825 0 1.567.403 2.082.918S20 4.175 20 5v3a1 1 0 1 1-2 0V5c0-.175-.097-.433-.332-.668S17.175 4 17 4H7c-.175 0-.433.097-.668.332S6 4.825 6 5v3a1 1 0 0 1-2 0V5c0-.825.403-1.567.918-2.082S6.175 2 7 2z"
    />
  </IconSvg>
);
export { Divider };
