// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const FileUp = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12.02 11.001a1 1 0 0 1 .198.023l.027.007a1 1 0 0 1 .462.262l3 3a1 1 0 1 1-1.414 1.414L13 14.414V18a1 1 0 1 1-2 0v-3.586l-1.293 1.293a1 1 0 1 1-1.414-1.414l3-3a1 1 0 0 1 .45-.259l.049-.013.033-.005A1 1 0 0 1 11.98 11L12 11z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M14.04 1.001a3.4 3.4 0 0 1 2.371.998l3.586 3.586.116.121A3.4 3.4 0 0 1 21 8v12a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h8zM6 3a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V9h-4a2 2 0 0 1-2-2V3zm9 4h3.584L15 3.416z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { FileUp };
