// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Filter = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M15 18a1 1 0 1 1 0 2H9a1 1 0 1 1 0-2zM18 11a1 1 0 1 1 0 2H6a1 1 0 1 1 0-2zM22 4a1 1 0 1 1 0 2H2a1 1 0 0 1 0-2z"
    />
  </IconSvg>
);
export { Filter };
