// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
/** @deprecated This icon is no longer available in the Figma source. It will be removed in a future version. */
const FilterNotification = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M19 9a2.9 2.9 0 0 1-2.125-.875A2.9 2.9 0 0 1 16 6q0-1.25.875-2.125A2.9 2.9 0 0 1 19 3q1.25 0 2.125.875T22 6t-.875 2.125A2.9 2.9 0 0 1 19 9M14.404 8A5 5 0 0 1 14 6H3v2zM10 16v2h4v-2zM6 11v2h12v-2z"
    />
  </IconSvg>
);
export { FilterNotification };
