// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const FoodBred = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M20.77 3.518c-1.134-1.134-3.533-1.419-6.23-.79A1.61 1.61 0 0 0 13.376 4.8l.183.546a.8.8 0 1 1-1.519.507l-.322-.967a.92.92 0 0 0-1.33-.504q-.2.113-.398.234c-.97.59-1.423 1.758-1.064 2.834l.632 1.897a.8.8 0 1 1-1.518.506l-.617-1.847a.705.705 0 0 0-1.199-.24q-.31.357-.595.728a3.24 3.24 0 0 0-.591 2.762l.537 2.15a.8.8 0 0 1-1.552.388l-.448-1.793c-1.566 3.645-1.54 7.287-.057 8.77 1.229 1.228 2.472.977 3.45-.002L20.768 6.969c.978-.978 1.23-2.22 0-3.45"
    />
  </IconSvg>
);
export { FoodBred };
