// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Ghost = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M9.01 9a1 1 0 1 1 0 2H9a1 1 0 1 1 0-2zM15.01 9a1 1 0 1 1 0 2H15a1 1 0 1 1 0-2z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1a9 9 0 0 1 9 9v12a1 1 0 0 1-1.707.707L17 20.414l-1.793 1.793a1 1 0 0 1-1.414 0L12 20.414l-1.793 1.793a1 1 0 0 1-1.414 0L7 20.414l-2.293 2.293A1 1 0 0 1 3 22V10a9 9 0 0 1 9-9m0 2a7 7 0 0 0-7 7v9.586l1.293-1.293.076-.068a1 1 0 0 1 1.338.068L9.5 20.086l1.793-1.793.076-.068a1 1 0 0 1 1.338.068l1.793 1.793 1.793-1.793.076-.068a1 1 0 0 1 1.338.068L19 19.586V10a7 7 0 0 0-7-7"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Ghost };
