// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Grip = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M9 17a2 2 0 1 1 0 4 2 2 0 0 1 0-4M15 17a2 2 0 1 1 0 4 2 2 0 0 1 0-4M9 10a2 2 0 1 1 0 4 2 2 0 0 1 0-4M15 10a2 2 0 1 1 0 4 2 2 0 0 1 0-4M9 3a2 2 0 1 1 0 4 2 2 0 0 1 0-4M15 3a2 2 0 1 1 0 4 2 2 0 0 1 0-4"
    />
  </IconSvg>
);
export { Grip };
