// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Heading3 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M16.993 9.639c1.12-.659 2.344-.692 3.322-.23C21.284 9.865 22 10.818 22 12c0 .74-.278 1.45-.77 1.999.493.549.77 1.26.77 2.001 0 1.285-.724 2.397-1.84 2.9-1.134.51-2.518.331-3.76-.6a1 1 0 1 1 1.2-1.6c.758.569 1.374.54 1.74.375.383-.172.66-.56.66-1.075a1 1 0 0 0-1-1 1 1 0 1 1 0-2l.099-.005A1 1 0 0 0 20 12c0-.318-.184-.616-.54-.783-.346-.164-.873-.196-1.453.145a1 1 0 0 1-1.014-1.723M12 5a1 1 0 0 1 1 1v12a1 1 0 1 1-2 0v-5H5v5a1 1 0 1 1-2 0V6a1 1 0 0 1 2 0v5h6V6a1 1 0 0 1 1-1"
    />
  </IconSvg>
);
export { Heading3 };
