// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Hide = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M1.293 1.293a1 1 0 0 1 1.414 0l20 20a1 1 0 0 1-1.414 1.414l-3.98-3.98a11.75 11.75 0 0 1-9.037.668 11.75 11.75 0 0 1-7.14-6.665l-.012-.035a2 2 0 0 1 0-1.391l.013-.034a11.75 11.75 0 0 1 3.806-4.913l-3.65-3.65a1 1 0 0 1 0-1.414m5.08 6.494A9.75 9.75 0 0 0 3 12a9.75 9.75 0 0 0 5.91 5.498 9.75 9.75 0 0 0 4.123.447 9.8 9.8 0 0 0 2.774-.723l-1.777-1.777a4 4 0 0 1-5.476-5.476zm3.695 3.696a1.998 1.998 0 0 0 2.448 2.447z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M10.614 4.083A11.745 11.745 0 0 1 22.67 10.83l.192.44.013.034a2 2 0 0 1 0 1.391l-.013.034a11.8 11.8 0 0 1-1.579 2.721 1 1 0 1 1-1.58-1.225 9.8 9.8 0 0 0 1.295-2.226 9.745 9.745 0 0 0-10.147-5.93 1 1 0 0 1-.237-1.985"
    />
  </IconSvg>
);
export { Hide };
