// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const House = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 .999c.62 0 1.223.193 1.727.548l.21.162.004.004 6.995 5.996.123.108A3 3 0 0 1 22 10v9a3.003 3.003 0 0 1-3 3H5a3 3 0 0 1-3-3v-9a3 3 0 0 1 1.063-2.291l6.996-5.996.005-.004A3 3 0 0 1 12 .999M12 3a1 1 0 0 0-.646.236L4.359 9.23l-.005.005A1 1 0 0 0 4 10v9a1 1 0 0 0 1 1h3v-7a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v7h3a1 1 0 0 0 1-1v-9a1 1 0 0 0-.355-.764l-.004-.005-6.995-5.996A1 1 0 0 0 12 3m-2 17h4v-7h-4z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { House };
