// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Icon5CircleFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2M9.662 7.013a.2.2 0 0 0-.2.19l-.256 4.988a.2.2 0 0 0 .2.21h2.407q.61 0 1.026.181.415.166.637.498.22.32.221.79 0 .429-.207.762a1.37 1.37 0 0 1-.582.513q-.36.18-.845.18-.706 0-1.233-.36-.45-.33-.826-.988a.206.206 0 0 0-.286-.077l-1.288.796a.195.195 0 0 0-.066.268 4.3 4.3 0 0 0 1.427 1.455q.928.567 2.271.568.999 0 1.802-.388a3 3 0 0 0 1.26-1.108q.471-.72.472-1.704 0-.943-.388-1.621-.388-.679-1.206-1.053-.804-.374-2.106-.374h-.537a.2.2 0 0 1-.199-.21l.089-1.636a.2.2 0 0 1 .2-.19h3.6a.2.2 0 0 0 .2-.2v-1.29a.2.2 0 0 0-.2-.2z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Icon5CircleFilled };
