// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Keyboard = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M17 15a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2zM8.01 11a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2zM12.01 11a1 1 0 1 1 0 2H12a1 1 0 1 1 0-2zM16.01 11a1 1 0 1 1 0 2H16a1 1 0 1 1 0-2zM6.01 7a1 1 0 0 1 0 2H6a1 1 0 0 1 0-2zM10.01 7a1 1 0 1 1 0 2H10a1 1 0 1 1 0-2zM14.01 7a1 1 0 1 1 0 2H14a1 1 0 1 1 0-2zM18.01 7a1 1 0 0 1 0 2H18a1 1 0 1 1 0-2z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M20 3a3 3 0 0 1 3 3v12a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3zM4 5a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Keyboard };
