// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Link = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M10.425 8.01a6 6 0 0 1 4.375 2.391A1 1 0 1 1 13.2 11.6a4 4 0 0 0-2.917-1.594 4 4 0 0 0-3.115 1.162l-2.989 2.987a4.002 4.002 0 0 0 5.658 5.656l1.697-1.697a1 1 0 1 1 1.414 1.414l-1.723 1.723a6 6 0 0 1-8.483-8.485l.012-.012 3-3a6 6 0 0 1 4.672-1.743"
    />
    <path
      fill="currentColor"
      d="M16.996 1.066a6 6 0 0 1 5.947 5.948 6 6 0 0 1-1.684 4.22l-3.012 3.013a6 6 0 0 1-9.048-.649 1 1 0 0 1 1.601-1.197 4 4 0 0 0 4.601 1.352 4 4 0 0 0 1.432-.92l2.987-2.988a4 4 0 0 0-.048-5.607 4 4 0 0 0-5.607-.049h-.001l-1.71 1.7a1 1 0 1 1-1.41-1.419l1.72-1.71.011-.01a6 6 0 0 1 4.22-1.684"
    />
  </IconSvg>
);
export { Link };
