// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Loader = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M21 11a1 1 0 0 1 1 1 10 10 0 1 1-6.91-9.511 1 1 0 1 1-.618 1.902 8.001 8.001 0 0 0-4.945 15.217A8 8 0 0 0 20 12a1 1 0 0 1 1-1"
    />
  </IconSvg>
);
export { Loader };
