// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Logout = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M9 2.5a1 1 0 0 1 0 2H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h4a1 1 0 1 1 0 2H5a3 3 0 0 1-3-3v-14a3 3 0 0 1 3-3z"
    />
    <path
      fill="currentColor"
      d="M15.293 6.793a1 1 0 0 1 1.414 0l5 5a1 1 0 0 1 .25.414l.015.062q.027.111.028.231-.001.084-.016.165a.991.991 0 0 1-.202.455 1 1 0 0 1-.075.087l-5 5a1 1 0 1 1-1.414-1.414l3.293-3.293H9a1 1 0 1 1 0-2h9.586l-3.293-3.293a1 1 0 0 1 0-1.414"
    />
  </IconSvg>
);
export { Logout };
