// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const MapPin = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12 1a9 9 0 0 1 9 9c0 2.834-1.553 5.603-3.206 7.775-1.677 2.203-3.584 3.956-4.54 4.78l-.052.044a2 2 0 0 1-2.457-.043c-.955-.825-2.863-2.578-4.539-4.78C4.553 15.602 3 12.833 3 10a9 9 0 0 1 9-9m0 2a7 7 0 0 0-7 7c0 2.16 1.217 4.487 2.798 6.564 1.528 2.008 3.281 3.632 4.202 4.431.92-.799 2.674-2.423 4.202-4.43C17.783 14.487 19 12.159 19 10a7 7 0 0 0-7-7m0 3a4 4 0 1 1 0 8 4 4 0 0 1 0-8m0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4"
    />
  </IconSvg>
);
export { MapPin };
