// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Maximize = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M9.293 13.293a1 1 0 1 1 1.414 1.414L5.414 20H9a1 1 0 1 1 0 2H3a1 1 0 0 1-1-1v-6a1 1 0 1 1 2 0v3.586zM22 9a1 1 0 1 1-2 0V5.414l-5.293 5.293a1 1 0 1 1-1.414-1.414L18.586 4H15a1 1 0 1 1 0-2h6a1 1 0 0 1 1 1z"
    />
  </IconSvg>
);
export { Maximize };
