// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const MicOff = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M1.293 1.293a1 1 0 0 1 1.414 0l20 20a1 1 0 0 1-1.414 1.414l-4.389-4.389A8 8 0 0 1 13 19.937V22a1 1 0 0 1-2 0v-2.063a7.996 7.996 0 0 1-6.994-7.641L4 12v-2a1 1 0 0 1 2 0v2a6 6 0 0 0 7.17 5.885 6 6 0 0 0 2.306-.995l-1.449-1.449a4 4 0 0 1-1.248.48A4 4 0 0 1 8 12V9.414L1.294 2.707a1 1 0 0 1 0-1.414M10 11.999l.006.147a2 2 0 0 0 2.509 1.783L10 11.414z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M19 9a1 1 0 0 1 1 1v2.001c0 .471-.043.942-.126 1.405a1 1 0 0 1-1.969-.352Q18 12.532 18 12v-2a1 1 0 0 1 1-1M10.305 1.395a4 4 0 0 1 4.82 1.128A4 4 0 0 1 16 4.993V9.34a1 1 0 0 1-2 0V5.006l-.008-.168a2 2 0 0 0-3.778-.719 1 1 0 0 1-1.787-.9 4 4 0 0 1 1.879-1.824"
    />
  </IconSvg>
);
export { MicOff };
