// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const MusicFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M17.114 1.805a.85.85 0 0 1 .742.168q.317.258.317.702v3.71a.76.76 0 0 1-.168.494.8.8 0 0 1-.455.258l-4.551 1q-.297.068-.396.187-.088.118-.088.445v9.062q0 1.058-.357 1.83-.346.771-.91 1.256a3.9 3.9 0 0 1-1.226.722 3.7 3.7 0 0 1-1.267.237q-1.286 0-2.107-.751-.82-.752-.82-1.949 0-1.167.741-1.94.743-.771 2.276-1.097l1.582-.326q.603-.129.545-.802l-.02-10.951q0-.91 1.068-1.138z"
    />
  </IconSvg>
);
export { MusicFilled };
