// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Pause = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M9.315 3.5c.742 0 1.342.6 1.342 1.342v14.316c0 .741-.6 1.342-1.342 1.342H6.632c-.741 0-1.343-.6-1.343-1.342V4.842c0-.741.602-1.342 1.343-1.342zM17.368 3.5c.741 0 1.342.6 1.342 1.342v14.316c0 .741-.6 1.342-1.342 1.342h-2.684c-.741 0-1.342-.6-1.342-1.342V4.842c0-.741.6-1.342 1.342-1.342z"
    />
  </IconSvg>
);
export { Pause };
