// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const PhoneFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M7 1.7A2.3 2.3 0 0 1 9.3 4v3c0 .311-.063.62-.186.906l-.056.122a2.3 2.3 0 0 1-.496.66l-.159.133-.022.018-.468.351-.007.004a.7.7 0 0 0-.198.855l.001.003a13.7 13.7 0 0 0 6.241 6.24l.01.005a.7.7 0 0 0 .459.04l.111-.037a.7.7 0 0 0 .273-.215l.006-.007.355-.463c.212-.28.488-.513.808-.673l.122-.056c.286-.123.595-.186.906-.186h3a2.3 2.3 0 0 1 2.3 2.3v3a2.3 2.3 0 0 1-2.3 2.3A18.3 18.3 0 0 1 1.7 4 2.3 2.3 0 0 1 4 1.7z"
    />
  </IconSvg>
);
export { PhoneFilled };
