// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const PictureInPicture = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M21 13a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-8a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2zm-8 7h8v-5h-8z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M3 13a1 1 0 0 1 1 1v2a1 1 0 0 0 1 1h3a1 1 0 1 1 0 2H5a3 3 0 0 1-3-3v-2a1 1 0 0 1 1-1M8 3a1 1 0 0 1 1 1v6q-.001.084-.016.165a1 1 0 0 1-.084.268l-.021.042a1 1 0 0 1-.587.481l-.062.016-.034.008-.031.004A1 1 0 0 1 8 11H2a1 1 0 1 1 0-2h3.586L1.293 4.707a1 1 0 1 1 1.414-1.414L7 7.586V4a1 1 0 0 1 1-1M19 4a3 3 0 0 1 3 3v3a1 1 0 1 1-2 0V7a1 1 0 0 0-1-1h-7a1 1 0 1 1 0-2z"
    />
  </IconSvg>
);
export { PictureInPicture };
