// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Pin = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M16 1a3 3 0 0 1 0 6v3.76l.01.138a1 1 0 0 0 .545.756l.006.003 1.774.898.184.1A3 3 0 0 1 20 15.238V16a2 2 0 0 1-2 2h-5v4a1 1 0 1 1-2 0v-4H6a2 2 0 0 1-2-2v-.76l.008-.209a3 3 0 0 1 1.657-2.476l1.773-.898.007-.003a1 1 0 0 0 .545-.756L8 10.76V7a3 3 0 0 1 0-6zM8 3a1 1 0 0 0-.099 1.995l.296.015A2 2 0 0 1 10 7v3.76a3 3 0 0 1-1.66 2.681v.001l-1.778.9-.007.004A1 1 0 0 0 6 15.24V16h12v-.76a1 1 0 0 0-.555-.894l-.006-.003-1.78-.9A3 3 0 0 1 14 10.76V7a2 2 0 0 1 1.803-1.99l.296-.015A1 1 0 0 0 16 3z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Pin };
