// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Present = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path fill="currentColor" d="M17 20a1 1 0 1 1 0 2H7a1 1 0 1 1 0-2z" />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M10.645 7.002c.113 0 .224.03.322.086l4.066 2.352a.647.647 0 0 1 .237.883l-.047.07a.7.7 0 0 1-.19.167l-4.065 2.352-.076.037a.7.7 0 0 1-.247.05l-.085-.006a.7.7 0 0 1-.162-.044l-.076-.037a.7.7 0 0 1-.19-.166l-.046-.07a.65.65 0 0 1-.086-.324V7.648a.65.65 0 0 1 .645-.646"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M20 2a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H4a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3zM4 4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Present };
