// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Presentation = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M22 2a1 1 0 1 1 0 2v10a3 3 0 0 1-3 3h-4.586l3.293 3.293a1 1 0 1 1-1.414 1.414L12 17.414l-4.293 4.293a1 1 0 1 1-1.414-1.414L9.586 17H5a3 3 0 0 1-3-3V4a1 1 0 0 1 0-2zM4 14a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V4H4z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Presentation };
