// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Print = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M17 1a2 2 0 0 1 2 2v5h1a3 3 0 0 1 3 3v5a3 3 0 0 1-3 3h-1v2a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-2H4a3 3 0 0 1-3-3v-5a3 3 0 0 1 3-3h1V3a2 2 0 0 1 2-2zM7 21h10v-6H7zM4 10a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h1v-2a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v2h1a1 1 0 0 0 1-1v-5a1 1 0 0 0-1-1zm3-2h10V3H7z"
    />
  </IconSvg>
);
export { Print };
