// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Restore = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M21 2a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2v10a3 3 0 0 1-3 3h-2a1 1 0 1 1 0-2h2a1 1 0 0 0 1-1V9H5v10a1 1 0 0 0 1 1h2a1 1 0 1 1 0 2H6a3 3 0 0 1-3-3V9a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2zM3 7h18V4H3z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M12.02 11.001a1 1 0 0 1 .106.007q.018.002.035.006l.057.01.027.007a1 1 0 0 1 .292.126l.023.015q.078.052.147.121l3 3a1 1 0 1 1-1.414 1.414L13 14.414V21a1 1 0 1 1-2 0v-6.586l-1.293 1.293a1 1 0 1 1-1.414-1.414l3-3a1 1 0 0 1 .45-.259l.049-.013.033-.005A1 1 0 0 1 11.98 11L12 11z"
    />
  </IconSvg>
);
export { Restore };
