// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ScreenShareOff = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M13.793 6.793a1 1 0 1 1 1.414 1.414L13.414 10l1.793 1.793a1 1 0 1 1-1.414 1.414L12 11.414l-1.793 1.793a1 1 0 1 1-1.414-1.414L10.586 10 8.793 8.207a1 1 0 1 1 1.414-1.414L12 8.586z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M20 2a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3h-7v2h3a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2h3v-2H4a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3zM4 4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { ScreenShareOff };
