// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Send = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M3.28 2.013c.297-.043.602.004.872.136l17.989 8.495.094.049c.185.104.346.246.472.417l.06.087.053.092c.1.184.157.388.173.597q.006.056.007.113a1.5 1.5 0 0 1-.765 1.308l-.094.049L4.148 21.85h.001a1.499 1.499 0 0 1-2.05-1.885l2.837-7.617a1 1 0 0 0 0-.699L2.098 4.035 2.06 3.93a1.5 1.5 0 0 1-.025-.775l.03-.109A1.5 1.5 0 0 1 3.28 2.013M6.825 13l-.016.047-2.413 6.475L18.207 13zm-.016-2.048.016.048h11.386L4.396 4.477z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Send };
