// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Shapes = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M9 12.76a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2zm-5 7h5v-5H4zM17.5 12.76a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9m0 2a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M12.17 1.407q.218.02.425.095l.2.087.187.114c.18.124.334.283.454.467l.011.017L17.15 8.13a1.7 1.7 0 0 1 .262.705l.012.115.003.116a1.7 1.7 0 0 1-1.694 1.693H8.301a1.7 1.7 0 0 1-1.509-.845 1.7 1.7 0 0 1 .043-1.777l3.72-5.91v.001a1.7 1.7 0 0 1 1.396-.828zM8.807 8.759h6.378l-3.173-5.094z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Shapes };
