// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Share = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M20 11a1 1 0 0 1 1 1v8a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3v-8a1 1 0 1 1 2 0v8a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-8a1 1 0 0 1 1-1"
    />
    <path
      fill="currentColor"
      d="M12.02 1.001q.027 0 .053.002a1 1 0 0 1 .145.021l.027.007a1 1 0 0 1 .462.262l4 4a1 1 0 1 1-1.414 1.414L13 4.414V15a1 1 0 1 1-2 0V4.414L8.707 6.707a1 1 0 1 1-1.414-1.414l4-4q.094-.093.208-.16l.044-.023a1 1 0 0 1 .197-.076l.05-.013.033-.005A1 1 0 0 1 11.98 1L12 1z"
    />
  </IconSvg>
);
export { Share };
