// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ShieldPause = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M10 8a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0V9a1 1 0 0 1 1-1M14 8a1 1 0 0 1 1 1v6a1 1 0 1 1-2 0V9a1 1 0 0 1 1-1"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 .999a2.17 2.17 0 0 1 1.41.522l.008.006C15.058 2.961 17.323 4 19 4a2 2 0 0 1 2 2v7c0 2.764-.98 4.89-2.554 6.505-1.547 1.587-3.626 2.64-5.777 3.39l-.008.003a2 2 0 0 1-1.317-.013l-.018-.006-.005-.001c-2.149-.744-4.221-1.793-5.765-3.374C3.979 17.889 3 15.764 3 13V6a2 2 0 0 1 2-2c1.676 0 3.952-1.048 5.582-2.473l.009-.006A2.17 2.17 0 0 1 12 .999M12 3a.17.17 0 0 0-.11.041l-.001-.001C10.039 4.652 7.32 6 5 6v7c0 2.235.77 3.861 1.986 5.106 1.243 1.273 2.998 2.194 5.01 2.89l.023.006c2.005-.7 3.754-1.62 4.995-2.894C18.229 16.862 19 15.236 19 13V6c-2.32 0-5.03-1.337-6.89-2.96A.17.17 0 0 0 12 3"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { ShieldPause };
