// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Sparkle = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <g clipPath="url(#a)">
      <path
        fill="currentColor"
        d="M12 .998a2 2 0 0 1 1.926 1.462l.04.17.003.018a9 9 0 0 0 7.038 7.318l.345.065.018.003a2 2 0 0 1 0 3.932l-.018.003a9 9 0 0 0-7.383 7.383l-.003.018a2 2 0 0 1-3.932 0l-.003-.018a9 9 0 0 0-7.383-7.383l-.018-.003a2 2 0 0 1 0-3.932l.018-.003a9 9 0 0 0 7.383-7.383l.003-.018A2 2 0 0 1 11.999.998m0 2A11 11 0 0 1 2.996 12 11 11 0 0 1 12 21.002 11 11 0 0 1 21.002 12 11 11 0 0 1 12 2.997"
      />
    </g>
    <defs>
      <clipPath id="a">
        <path fill="currentColor" d="M0 0h24v24H0z" />
      </clipPath>
    </defs>
  </IconSvg>
);
export { Sparkle };
