// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const TagOff = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M1.293 1.293a1 1 0 0 1 1.414 0l20 20a1 1 0 0 1-1.414 1.414l-3.835-3.835-.96.96a3 3 0 0 1-2.121.878H5.064a3.43 3.43 0 0 1-3.415-3.416v-9.31A3.43 3.43 0 0 1 3.525 4.94L1.293 2.706a1 1 0 0 1 0-1.414M5.07 6.567a1.43 1.43 0 0 0-1.42 1.422v9.3a1.426 1.426 0 0 0 1.42 1.42l9.306.001c.232 0 .457-.08.635-.227l.073-.066.959-.959-10.89-10.89z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M14.377 4.568c.795 0 1.56.316 2.122.878l5.071 5.072a3 3 0 0 1 0 4.242l-.535.534a1 1 0 0 1-1.413-1.415l.534-.533a1 1 0 0 0 0-1.414L15.085 6.86l-.073-.066a1 1 0 0 0-.635-.227H9.998a1 1 0 1 1 0-1.999z"
    />
  </IconSvg>
);
export { TagOff };
