// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const TodoList = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M8.293 14.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 1 1 1.414-1.414L5 17.586zM21 18a1 1 0 1 1 0 2h-8a1 1 0 1 1 0-2zM21 11a1 1 0 1 1 0 2h-8a1 1 0 1 1 0-2z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M8 3a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2zM4 9h4V5H4z"
      clipRule="evenodd"
    />
    <path fill="currentColor" d="M21 4a1 1 0 1 1 0 2h-8a1 1 0 1 1 0-2z" />
  </IconSvg>
);
export { TodoList };
