// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ToggleHeading1 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M15.104 6.823a1 1 0 0 1 1 1v4.16l.001.017v4.1770000000000005a1 1 0 0 1-2 0V13h-3.569v3.177a1 1 0 0 1-2 0V7.823a1 1 0 0 1 2 0V11h3.568V7.823a1 1 0 0 1 1-1M20.118 9.775a1 1 0 0 1 1.555.832v5.57a1 1 0 0 1-2 0v-3.701l-.533.356a1 1 0 0 1-1.11-1.664zM2.293 8.293a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 1 1-1.414-1.414L4.586 12 2.293 9.707a1 1 0 0 1 0-1.414"
    />
  </IconSvg>
);
export { ToggleHeading1 };
