// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Underline = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M20 19a1 1 0 1 1 0 2H4a1 1 0 1 1 0-2zM18 3a1 1 0 0 1 1 1v6a7.001 7.001 0 1 1-14 0V4a1 1 0 0 1 2 0v6a5 5 0 0 0 10 0V4a1 1 0 0 1 1-1"
    />
  </IconSvg>
);
export { Underline };
