// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Undo = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M8.293 3.293a1 1 0 1 1 1.414 1.414L6.414 8H14.5a6.5 6.5 0 0 1 0 13H11a1 1 0 1 1 0-2h3.5a4.501 4.501 0 0 0 3.182-7.682A4.5 4.5 0 0 0 14.5 10H6.414l3.293 3.293a1 1 0 0 1-1.414 1.414l-5-5a1 1 0 0 1-.25-.416l-.013-.05a1 1 0 0 1-.002-.473q.007-.03.015-.06a1 1 0 0 1 .096-.213q.064-.111.154-.202z"
    />
  </IconSvg>
);
export { Undo };
