// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const UserLock = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M9.5 14a1 1 0 1 1 0 2H7a3 3 0 0 0-3 3v2a1 1 0 1 1-2 0v-2a5 5 0 0 1 5-5z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M17 11a3 3 0 0 1 3 3v1h.1a1.9 1.9 0 0 1 1.9 1.9v3.2a1.9 1.9 0 0 1-1.9 1.9h-6.2a1.9 1.9 0 0 1-1.9-1.9v-3.2a1.9 1.9 0 0 1 1.9-1.9h.1v-1a3 3 0 0 1 3-3m-3 9h6v-3h-6zm3-7a1 1 0 0 0-1 1v1h2v-1a1 1 0 0 0-1-1M10 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10m0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { UserLock };
