// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const UserSearch = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M10.3 14a1 1 0 1 1 0 2H7a3 3 0 0 0-3 3v2a1 1 0 1 1-2 0v-2a5 5 0 0 1 5-5z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M17 13a4 4 0 0 1 3.445 6.03l1.263 1.263a1 1 0 0 1-1.414 1.414l-1.263-1.263A4 4 0 1 1 17 13m0 2a2 2 0 1 0 1.266 3.547 1 1 0 0 1 .28-.281A2 2 0 0 0 17 15M10 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10m0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { UserSearch };
