// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Volume2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M10.088 3.01c.25-.03.502-.005.741.074l.118.044.115.052c.224.113.42.274.576.472l.074.103.066.107c.145.255.221.544.222.838v14.597l-.005.126a1.704 1.704 0 0 1-2.907 1.08l-3.384-3.385A.4.4 0 0 0 5.42 17H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h2.419a.4.4 0 0 0 .285-.118l3.387-3.386c.238-.238.542-.4.872-.466zM3 15h2.416a2.4 2.4 0 0 1 1.704.706l2.88 2.88V5.414l-2.88 2.88a2.4 2.4 0 0 1-1.704.705H3zM16 12a4 4 0 0 0-.8-2.4 1 1 0 1 1 1.6-1.2 6 6 0 0 1 0 7.2 1 1 0 1 1-1.6-1.2A4 4 0 0 0 16 12"
    />
    <path
      fill="currentColor"
      d="M21 12a8 8 0 0 0-2.343-5.657 1 1 0 1 1 1.414-1.414 10 10 0 0 1 0 14.143 1 1 0 0 1-1.414-1.415A8 8 0 0 0 21 12"
    />
  </IconSvg>
);
export { Volume2 };
