// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Archive = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1.002a3 3 0 0 1 1.495.4h.001l7 4 .004.002A3 3 0 0 1 22 8v8.002a3 3 0 0 1-1.5 2.595l-.004.003-7 4v-.001a3 3 0 0 1-1.389.396 1 1 0 0 1-.211 0 3 3 0 0 1-1.392-.396l-7-4-.004-.002A3 3 0 0 1 2 16V7.999l.007-.197A3 3 0 0 1 3.5 5.404l.004-.003 7-4c.455-.262.97-.4 1.496-.4M4 15.999l.009.13a1 1 0 0 0 .487.732L11 20.577v-7.999L4 8.561zm13.053-5.748a1 1 0 0 1-.124.071L13 12.578v8l6.504-3.717A1 1 0 0 0 20 16V8.56zM5.017 6.838 12 10.847l2.484-1.428-6.988-3.998zM12 3.002a1 1 0 0 0-.5.134l-.004.002L9.513 4.27l6.982 3.995 2.486-1.427-6.477-3.7-.004-.002a1 1 0 0 0-.5-.134"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Archive };
