// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ArrowDownRight = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M17 6a1 1 0 0 1 1 1v10q-.001.084-.016.165a.991.991 0 0 1-.105.31 1 1 0 0 1-.59.482l-.049.012q-.023.006-.045.01-.015.004-.03.005A1 1 0 0 1 17 18H7a1 1 0 1 1 0-2h7.586L6.293 7.707a1 1 0 1 1 1.414-1.414L16 14.586V7a1 1 0 0 1 1-1"
    />
  </IconSvg>
);
export { ArrowDownRight };
