// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ArrowDownLeft = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M16.293 6.293a1 1 0 1 1 1.414 1.414L9.414 16H17a1 1 0 1 1 0 2H7q-.085-.001-.166-.016-.015-.001-.031-.005l-.034-.007-.062-.016a1 1 0 0 1-.257-.121 1 1 0 0 1-.33-.36l-.02-.042a1 1 0 0 1-.057-.141A1.003 1.003 0 0 1 6 17V7a1 1 0 0 1 2 0v7.586z"
    />
  </IconSvg>
);
export { ArrowDownLeft };
