// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ArrowSquarepath = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M21 12a1 1 0 0 1 1 1v1a5 5 0 0 1-5 5H5.414l2.293 2.293a1 1 0 0 1-1.414 1.414l-4-4a1 1 0 0 1-.193-.274 1 1 0 0 1-.057-.143l-.013-.05a1 1 0 0 1 .014-.534 1 1 0 0 1 .121-.256q.056-.085.128-.157l4-4a1 1 0 1 1 1.414 1.414L5.414 17H17a3 3 0 0 0 3-3v-1a1 1 0 0 1 1-1M16.293 1.293a1 1 0 0 1 1.414 0l4 4a1 1 0 0 1 .25.414l.015.062q.027.111.028.231-.001.125-.031.24l-.013.051a1 1 0 0 1-.125.263 1 1 0 0 1-.124.153l-4 4a1 1 0 1 1-1.414-1.414L18.586 7H7a3 3 0 0 0-3 3v1a1 1 0 0 1-2 0v-1a5 5 0 0 1 5-5h11.586l-2.293-2.293a1 1 0 0 1 0-1.414"
    />
  </IconSvg>
);
export { ArrowSquarepath };
