// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ArrowLeftRight = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M15.293 12.293a1 1 0 0 1 1.414 0l4 4a1 1 0 0 1 .25.414l.015.062q.027.111.028.231-.001.125-.031.24l-.013.051a1 1 0 0 1-.165.317 1 1 0 0 1-.084.1l-4 4a1 1 0 1 1-1.414-1.415L17.586 18H4a1 1 0 0 1 0-2h13.586l-2.293-2.293a1 1 0 0 1 0-1.414M7.293 2.293a1 1 0 1 1 1.414 1.414L6.414 6H20a1 1 0 1 1 0 2H6.414l2.293 2.293a1 1 0 0 1-1.414 1.414l-4-4a1 1 0 0 1-.193-.274 1 1 0 0 1-.057-.142l-.013-.05a1 1 0 0 1-.003-.472l.016-.062a1 1 0 0 1 .122-.257q.056-.085.128-.157z"
    />
  </IconSvg>
);
export { ArrowLeftRight };
