// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ArrowUp = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M19.707 11.293a1 1 0 1 1-1.414 1.414L13 7.414V19a1 1 0 1 1-2 0V7.414l-5.293 5.293a1 1 0 1 1-1.414-1.414l7-7a1 1 0 0 1 1.414 0z"
    />
  </IconSvg>
);
export { ArrowUp };
