// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Ban = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1c6.075 0 11 4.925 11 11s-4.925 11-11 11S1 18.075 1 12 5.925 1 12 1M4.97 6.383A9 9 0 0 0 17.616 19.03zM12 3a8.96 8.96 0 0 0-5.616 1.969L19.03 17.616A9 9 0 0 0 12 3"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Ban };
