// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const BellOff = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12.865 20.5a1 1 0 0 1 1.733 1 3 3 0 0 1-5.197 0 1 1 0 0 1 1.733-1A1 1 0 0 0 12 21a1 1 0 0 0 .865-.5"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M1.293 1.293a1 1 0 0 1 1.414 0l4.252 4.252.017.018 15.731 15.73a1 1 0 0 1-1.414 1.414L16.586 18H3.999a2 2 0 0 1-1.48-3.346l.023-.023c.666-.686 1.241-1.29 1.682-2.222.412-.872.733-2.1.771-4.016L4.999 8c0-.483.051-.965.15-1.436L1.293 2.707a1 1 0 0 1 0-1.414m5.702 7.116c-.04 2.138-.4 3.664-.963 4.855C5.442 14.513 4.66 15.32 4 16h10.586z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M11.658 1.009A7 7 0 0 1 19 8c0 2.482.707 4.256 1.537 5.493a1 1 0 0 1-1.66 1.114C17.833 13.052 17 10.892 17 8a5 5 0 0 0-5.244-4.994 5 5 0 0 0-2.532.836 1.001 1.001 0 0 1-1.112-1.663 7 7 0 0 1 3.546-1.17"
    />
  </IconSvg>
);
export { BellOff };
