// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Bell = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12.865 20.5a1 1 0 0 1 1.733 1 3.002 3.002 0 0 1-5.197 0 1 1 0 0 1 1.733-1 1 1 0 0 0 1.366.366 1 1 0 0 0 .365-.366"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M11.999 1a7 7 0 0 1 7 7c0 2.145.336 3.479.775 4.41.33.698.738 1.212 1.201 1.715l.482.506.021.023a2 2 0 0 1-1.335 3.341L20 18h-16a2 2 0 0 1-1.83-1.193 2 2 0 0 1 .353-2.155l.02-.022c.665-.686 1.241-1.288 1.682-2.22.439-.931.775-2.265.775-4.41a7 7 0 0 1 7-7m0 2a5 5 0 0 0-5 5c0 2.354-.37 3.998-.967 5.264C5.442 14.514 4.658 15.32 4 16h15.999c-.66-.68-1.442-1.487-2.032-2.736-.598-1.266-.968-2.91-.968-5.264a5 5 0 0 0-5-5"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Bell };
