// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Bold = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M18 16a3 3 0 0 0-3-3H7v6h8a3 3 0 0 0 3-3m2 0a5 5 0 0 1-5 5H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7a5 5 0 0 1 3.535 8.535q-.05.05-.103.098A5 5 0 0 1 20 16M7 11h7a3 3 0 0 0 0-6H7z"
    />
  </IconSvg>
);
export { Bold };
