// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Bolt = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M13.225 1.023a1.5 1.5 0 0 1 .866.096l.115.056.109.065a1.5 1.5 0 0 1 .506.551l.056.115.044.119a1.5 1.5 0 0 1 .023.87l-.01.039-1.92 6.02-.017.046H20a2 2 0 0 1 1.556 3.26l-.058.066-9.9 10.2h-.002a1.498 1.498 0 0 1-2.54-1.421l.011-.04 1.92-6.019.017-.046H4a2.002 2.002 0 0 1-1.556-3.26q.027-.035.059-.067l9.9-10.2c.219-.233.506-.392.822-.45M4.003 13H11a2 2 0 0 1 1.988 1.75c.038.305.002.613-.098.903h.003l-1.266 3.971L19.997 11H13a2 2 0 0 1-1.988-1.75 2 2 0 0 1 .097-.904h-.002l1.266-3.972z"
    />
  </IconSvg>
);
export { Bolt };
