// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Book2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M8 2a5 5 0 0 1 4 2.001A5 5 0 0 1 16 2h5a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2h-6a2 2 0 0 0-2 2 1 1 0 1 1-2 0 2 2 0 0 0-2-2H3a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2zM3 17h6c.708 0 1.397.189 2 .537V7a3 3 0 0 0-3-3H3zM16 4a3 3 0 0 0-3 3v10.537A4 4 0 0 1 15 17h6V4z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Book2 };
