// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Building2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M8.01 13a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2zM12.01 13a1 1 0 1 1 0 2H12a1 1 0 1 1 0-2zM16.01 13a1 1 0 1 1 0 2H16a1 1 0 1 1 0-2zM8.01 9a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2zM12.01 9a1 1 0 1 1 0 2H12a1 1 0 1 1 0-2zM16.01 9a1 1 0 1 1 0 2H16a1 1 0 1 1 0-2zM8.01 5a1 1 0 0 1 0 2H8a1 1 0 0 1 0-2zM12.01 5a1 1 0 1 1 0 2H12a1 1 0 1 1 0-2zM16.01 5a1 1 0 1 1 0 2H16a1 1 0 1 1 0-2z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M18 1a3 3 0 0 1 3 3v16a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3zM6 3a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h2v-2a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2h2a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1zm4 18h4v-2h-4z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Building2 };
