// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const Burger = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M2.967 18.39a.92.92 0 0 1-.687-.3 1 1 0 0 1-.28-.706q0-.396.28-.686a.92.92 0 0 1 .687-.29h18.066q.397 0 .677.29.29.29.29.686 0 .406-.29.706-.28.3-.677.3zm0-5.42a.94.94 0 0 1-.687-.29.99.99 0 0 1-.28-.695q0-.406.28-.696.28-.3.687-.3h18.066q.397 0 .677.3a.95.95 0 0 1 .29.696.97.97 0 0 1-.29.696.9.9 0 0 1-.677.29zm0-5.398a.94.94 0 0 1-.687-.29.99.99 0 0 1-.28-.696q0-.406.28-.696a.92.92 0 0 1 .687-.29h18.066q.397 0 .677.29a.95.95 0 0 1 .29.696.97.97 0 0 1-.29.696.9.9 0 0 1-.677.29z"
    />
  </svg>
);
export { Burger };
