// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Callout = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M16 7.5a1 1 0 0 1 1 1v2a1 1 0 1 1-2 0v-1h-2v5h1a1 1 0 1 1 0 2h-4a1 1 0 1 1 0-2h1v-5H9v1a1 1 0 1 1-2 0v-2a1 1 0 0 1 1-1z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M19 2a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3zM5 4a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Callout };
