// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const CameraSwitch = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M20 4a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3h-2.586l1.293 1.293a1 1 0 0 1-1.414 1.414l-3-3a1 1 0 0 1-.193-.274 1 1 0 0 1-.057-.142l-.013-.05a1 1 0 0 1-.003-.472l.016-.062a1 1 0 0 1 .122-.257q.056-.085.128-.157l3-3a1 1 0 1 1 1.414 1.414L17.414 18H20a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1h-7a1 1 0 0 1 0-2zM5.293 1.293a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 .249.414l.016.062Q9.999 4.88 10 5a1 1 0 0 1-.031.24l-.013.051a1 1 0 0 1-.165.317 1 1 0 0 1-.084.1l-3 3a1 1 0 0 1-1.414-1.415L6.586 6H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h7a1 1 0 0 1 0 2H4a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3h2.586L5.293 2.707a1 1 0 0 1 0-1.414"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8m0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { CameraSwitch };
