// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Checkmark2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M10.119 19.885q-.656 0-1.118-.581l-4.709-5.89q-.173-.21-.254-.41a1.2 1.2 0 0 1-.073-.409q0-.472.309-.781.318-.31.8-.31.555 0 .936.5l4.072 5.227 7.89-12.535q.21-.318.427-.445.219-.135.564-.136.472 0 .772.3.3.29.3.763 0 .191-.063.391-.065.19-.2.41l-8.544 13.316q-.4.59-1.11.59"
    />
  </IconSvg>
);
export { Checkmark2 };
