// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Chess = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1a3 3 0 0 1 1.676 5.487L15 11l2.217-2.883A3 3 0 1 1 23 7a3 3 0 0 1-2.247 2.9l-2.375 7.126A3 3 0 0 1 21 20v1a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-1a3 3 0 0 1 2.621-2.974L3.246 9.9A2.998 2.998 0 0 1 4 4a3 3 0 0 1 2.783 4.114L9 11l1.324-4.51A3 3 0 0 1 12 1M6 19a1 1 0 0 0-1 1v1h14v-1a1 1 0 0 0-1-1zm4.919-7.435v.001A2 2 0 0 1 8.29 12.87a2 2 0 0 1-.871-.645l-.002-.003-1.986-2.585q-.07.035-.143.068L7.721 17h8.558l2.431-7.295q-.072-.032-.14-.068l-1.986 2.584-.001.002a2 2 0 0 1-1.951.743 2 2 0 0 1-1.549-1.399l-.001-.002L12 7.879zM4 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2m16 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2m-8-3a1 1 0 1 0 0 2 1 1 0 0 0 0-2"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Chess };
