// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const ChevronDownward = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path fill="currentColor" d="M12 12.6 16.6 8 18 9.4l-6 6-6-6L7.4 8z" />
  </svg>
);
export { ChevronDownward };
