// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const ChevronUpward = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path fill="currentColor" d="m12 10.8-4.6 4.6L6 14l6-6 6 6-1.4 1.4z" />
  </svg>
);
export { ChevronUpward };
