// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const CloudDownload = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12 12a1 1 0 0 1 1 1v5.586l2.293-2.293a1 1 0 1 1 1.414 1.414l-4 4a1 1 0 0 1-.445.256l-.042.011q-.13.03-.262.023h-.019a1 1 0 0 1-.263-.052l-.019-.007a1 1 0 0 1-.122-.053l-.004-.002-.008-.005a1 1 0 0 1-.128-.083q-.013-.008-.026-.02l-.076-.068-4-4a1 1 0 0 1 1.414-1.414L11 18.586V13a1 1 0 0 1 1-1"
    />
    <path
      fill="currentColor"
      d="M8.14 2.047a8 8 0 0 1 6.7 2.484A8 8 0 0 1 16.415 7H17.5l.223.003a5.502 5.502 0 0 1 4.932 7.415 5.5 5.5 0 0 1-2.178 2.705 1 1 0 0 1-1.083-1.681A3.5 3.5 0 0 0 17.5 9h-1.79a1 1 0 0 1-.958-.715 6 6 0 0 0-6.397-4.25 6 6 0 0 0-3.303 10.48 1 1 0 0 1-1.318 1.507A8 8 0 0 1 2.127 5.909a8 8 0 0 1 6.012-3.862"
    />
  </IconSvg>
);
export { CloudDownload };
