// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Compass = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M15.924 6.812a1 1 0 0 1 1.265 1.264l-1.804 5.411a3 3 0 0 1-1.898 1.898l-5.41 1.804a1 1 0 0 1-1.265-1.265l1.803-5.411a3 3 0 0 1 1.898-1.898zm-4.778 3.7a1 1 0 0 0-.633.633L9.34 14.658l3.514-1.17.107-.044a1 1 0 0 0 .525-.59l1.171-3.513z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1c6.075 0 11 4.925 11 11s-4.925 11-11 11S1 18.075 1 12 5.925 1 12 1m0 2a9 9 0 1 0 0 18 9 9 0 0 0 0-18"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Compass };
