// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Computer = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M18 4a3.003 3.003 0 0 1 3 3v8.526l.007.117a1 1 0 0 0 .1.332l1.066 2.125a2 2 0 0 1-.086 1.955 2 2 0 0 1-1.707.944L3.62 21a2 2 0 0 1-1.793-2.9l1.068-2.125.045-.107q.06-.165.06-.342V7a3 3 0 0 1 3-3zM4.624 16.987 3.614 19V19h16.774l-.001-.001-1.011-2.012zM6 6a1 1 0 0 0-1 1v7.987h14V7a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Computer };
