// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Controls = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M17 13a4 4 0 1 1-3.874 5H5a1 1 0 1 1 0-2h8.126c.444-1.725 2.01-3 3.874-3m0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4M7 3a4 4 0 0 1 3.874 3H19a1 1 0 1 1 0 2h-8.126A4.002 4.002 0 0 1 3 7a4 4 0 0 1 4-4m0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Controls };
