// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
/** @deprecated This icon is no longer available in the Figma source. It will be removed in a future version. */
const CsvExport = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M3 20V2h18v10h-8v8zM19 4h-6v6h6zM5 4v6h6V4zm0 14h6v-6H5z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="m19 22.5-4-4 1.4-1.4 1.6 1.6V14h2v4.7l1.6-1.6 1.4 1.4z"
    />
  </IconSvg>
);
export { CsvExport };
