// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const CsvImport = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M3 20V2h18v10h-8v8zM19 4h-6v6h6zM5 4v6h6V4zm0 14h6v-6H5z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="m15 18 4-4 4 4-1.4 1.4-1.6-1.6v5.175h-2V17.8l-1.6 1.6z"
    />
  </svg>
);
export { CsvImport };
