// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
/** @deprecated This icon is no longer available in the Figma source. It will be removed in a future version. */
const DocSlash = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M2.148 1.445q.293 0 .505.204l19.711 19.702q.203.212.195.496a.72.72 0 0 1-.195.504.68.68 0 0 1-.496.204.7.7 0 0 1-.504-.204L1.644 2.649a.68.68 0 0 1-.204-.496q0-.3.205-.504a.7.7 0 0 1 .503-.204M5.526 8.385V19.07q0 .657.343 1.01t1.038.353h9.827q.42-.001.71-.13l1.464 1.464q-.753.541-2.021.542H6.745q-1.534 0-2.314-.79t-.78-2.333V6.509zM16.887 1.691q1.534 0 2.314.8.78.79.781 2.324v12.309l-1.867-1.867V4.938q0-.666-.342-1.018-.344-.362-1.039-.362H6.907q-.245 0-.446.045l-1.51-1.51q.708-.402 1.794-.402z"
    />
    <path
      fill="currentColor"
      d="M11.127 13.985H8.335a.6.6 0 0 1-.438-.17.57.57 0 0 1-.171-.42q0-.256.171-.428.172-.18.438-.18h1.593zM15.307 9.53a.58.58 0 0 1 .427.17.57.57 0 0 1 .172.42.62.62 0 0 1-.172.438.58.58 0 0 1-.427.17h-1.72l-1.2-1.199zM15.307 6.272a.582.582 0 0 1 .6.6.6.6 0 0 1-.173.429.57.57 0 0 1-.427.18H10.34L9.13 6.272z"
    />
  </IconSvg>
);
export { DocSlash };
