// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Edit = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M19.182 1a3.82 3.82 0 0 1 2.83 6.383l-.131.137-2.091 2.09a1 1 0 0 1-.083.097 1 1 0 0 1-.098.083L8.533 20.87a3 3 0 0 1-1.245.745l-4.353 1.32-.003.002a1.501 1.501 0 0 1-1.87-1.867l.002-.004 1.32-4.352.002-.003c.144-.47.402-.898.75-1.245L14.209 4.389a1 1 0 0 1 .18-.18l2.091-2.09A3.82 3.82 0 0 1 19.182 1M4.548 16.883a1 1 0 0 0-.25.415l-1.049 3.451 3.457-1.048.114-.042q.17-.076.301-.206L17.58 8.993l-2.572-2.572zM19.182 3a1.82 1.82 0 0 0-1.287.532l-1.474 1.475 2.572 2.572 1.474-1.474.12-.133a1.82 1.82 0 0 0-.12-2.439A1.82 1.82 0 0 0 19.182 3"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Edit };
