// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const Edit = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M17.789 8.125 6.67 19.245l-2.394.92q-.218.079-.396-.1a.37.37 0 0 1-.089-.405l.97-2.325L15.89 6.216zM18.71 3.813q.424-.03.79.326l.386.395q.366.366.347.782-.02.415-.426.82l-1.068 1.06-1.92-1.91 1.07-1.058q.395-.386.82-.415"
    />
  </svg>
);
export { Edit };
