// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Enter = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M20 3a1 1 0 0 1 1 1v7a5 5 0 0 1-5 5H6.414l3.293 3.293a1 1 0 1 1-1.414 1.414l-5-5a1 1 0 0 1-.173-.232l-.02-.042a.99.99 0 0 1 .065-.983q.056-.085.128-.157l5-5a1 1 0 1 1 1.414 1.414L6.414 14H16a3 3 0 0 0 3-3V4a1 1 0 0 1 1-1"
    />
  </IconSvg>
);
export { Enter };
