// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ErrorFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1.5c5.799 0 10.5 4.701 10.5 10.5S17.799 22.5 12 22.5 1.5 17.799 1.5 12 6.201 1.5 12 1.5m0 13.4a1.1 1.1 0 1 0 0 2.2 1.1 1.1 0 0 0 0-2.2m-.005-8c-.605 0-1.095.493-1.095 1.1v4c0 .607.49 1.1 1.095 1.1s1.095-.493 1.095-1.1V8c0-.607-.49-1.1-1.095-1.1"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { ErrorFilled };
