// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
/** @deprecated This icon is no longer available in the Figma source. It will be removed in a future version. */
const Eye = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 8a4 4 0 1 1 0 8 4 4 0 0 1 0-8m0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 4.001a11.75 11.75 0 0 1 10.688 6.87l.174.4.013.034a2 2 0 0 1 0 1.391l-.013.034a11.752 11.752 0 0 1-17.398 5.285 11.75 11.75 0 0 1-4.327-5.286l-.013-.033a2 2 0 0 1 0-1.391l.013-.034A11.75 11.75 0 0 1 12 4.002m0 2A9.75 9.75 0 0 0 3 12a9.75 9.75 0 0 0 14.423 4.352A9.75 9.75 0 0 0 20.998 12 9.75 9.75 0 0 0 12 6.001"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Eye };
