// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Files = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M5 6a1 1 0 0 1 0 2 1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h8l.13-.009a1 1 0 0 0 .736-.491 1 1 0 0 1 1.732 1A3 3 0 0 1 13 23H5a3 3 0 0 1-3-3V9a3 3 0 0 1 3-3"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M15.002 1a3.4 3.4 0 0 1 2.411.999L21 5.586l.116.121A3.4 3.4 0 0 1 22 7.997L22 8v7a3 3 0 0 1-3 3h-8a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3zM11 3a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V9h-4a2 2 0 0 1-2-2V3zm5 4h3.586L16 3.414z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Files };
