// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const FileOtherFilled = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M6.744 22.612q-1.607 0-2.425-.828-.819-.828-.819-2.446V4.274q0-1.607.819-2.435Q5.137.999 6.744 1h4.552v7.547q0 1.857 1.857 1.857h7.467v8.934q0 1.607-.818 2.436-.82.838-2.426.838zm6.589-13.666q-.57 0-.57-.569V1.1q.34.04.68.28.349.24.719.618l5.45 5.53q.39.4.619.74.24.339.28.678z"
    />
  </svg>
);
export { FileOtherFilled };
