// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const FileOther = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M6.744 22.612q-1.607 0-2.425-.828-.819-.828-.819-2.446V4.274q0-1.607.819-2.435Q5.137.999 6.744 1h4.812q.63 0 1.098.09.469.08.869.31.4.219.818.648l5.231 5.32q.439.44.659.85.23.399.31.888.08.48.08 1.178v9.054q0 1.607-.82 2.436-.818.838-2.425.838zm.16-1.966h10.312q.73 0 1.088-.37.36-.37.36-1.058v-8.665h-5.381q-1.068 0-1.597-.529-.52-.529-.52-1.597v-5.47H6.915q-.728 0-1.088.379-.36.38-.36 1.068v14.814q0 .69.36 1.058.36.37 1.078.37m6.569-11.82h4.921l-5.5-5.6v5.011q0 .31.13.45.139.14.449.14"
    />
  </svg>
);
export { FileOther };
