// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const FileImport = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M6 20q-.824 0-1.412-.587A1.93 1.93 0 0 1 4 18V4q0-.824.588-1.412A1.93 1.93 0 0 1 6 2h7l6 6v3.025h-2V9h-5V4H6v14h6v2zM22 18.025l-4-4-4 4 1.4 1.4 1.6-1.6V23h2v-5.175l1.6 1.6z"
    />
  </svg>
);
export { FileImport };
