// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const FileDelete = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M14.04 1.001a3.4 3.4 0 0 1 2.373.998L20 5.586l.116.121A3.4 3.4 0 0 1 21 8v5a1 1 0 1 1-2 0V9h-4a2 2 0 0 1-2-2V3H6a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h5a1 1 0 1 1 0 2H6a3 3 0 0 1-3-3V4a3 3 0 0 1 3-3h8zM15 7h3.586L15 3.414z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M19.293 16.293a1 1 0 1 1 1.414 1.414L18.914 19.5l1.793 1.793a1 1 0 1 1-1.414 1.414L17.5 20.914l-1.793 1.793a1 1 0 1 1-1.414-1.414l1.793-1.793-1.793-1.793a1 1 0 1 1 1.414-1.414l1.793 1.793z"
    />
  </IconSvg>
);
export { FileDelete };
