// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
/** @deprecated This icon is no longer available in the Figma source. It will be removed in a future version. */
const FileFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M7.107 21.876q-1.498 0-2.26-.773-.764-.771-.764-2.279V4.789q0-1.498.763-2.27.763-.78 2.26-.781h4.242v7.032q0 1.73 1.73 1.73h6.958v8.326q0 1.497-.762 2.27-.763.78-2.26.78zM13.246 9.14q-.53 0-.53-.53V1.83q.315.037.632.26.325.224.67.577l5.079 5.153q.363.372.577.689.222.315.26.632z"
    />
  </IconSvg>
);
export { FileFilled };
