// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Filtered = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M15 18a1 1 0 1 1 0 2H9a1 1 0 1 1 0-2zM18 11a1 1 0 1 1 0 2H6a1 1 0 1 1 0-2z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M19 1a4 4 0 1 1 0 8 4 4 0 0 1 0-8m0 2a2 2 0 1 0 0 4 2 2 0 0 0 0-4"
      clipRule="evenodd"
    />
    <path fill="currentColor" d="M12 4a1 1 0 1 1 0 2H2a1 1 0 0 1 0-2z" />
  </IconSvg>
);
export { Filtered };
