// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const FolderTiny = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M2.657 19.028q.73.73 2.154.73h14.598q1.257 0 1.96-.73.703-.72.703-2.127V7.866q0-1.406-.738-2.136-.729-.729-2.145-.729h-8.173q-.475 0-.8-.123a2.7 2.7 0 0 1-.695-.413l-.5-.413a3 3 0 0 0-.59-.396q-.28-.15-.615-.21a4.4 4.4 0 0 0-.79-.062H4.537q-1.23 0-1.925.712-.685.702-.685 2.092V16.9q0 1.407.73 2.127m16.418-1.002H4.916q-.616 0-.94-.316-.317-.316-.317-.958v-6.706h16.69v6.715q0 .633-.333.949-.334.316-.94.316m1.275-9.5H3.66v-2.19q0-.605.316-.913.315-.317.905-.317h1.696q.465 0 .782.132.326.123.695.422l.5.413q.3.246.58.396.29.14.625.202.342.06.8.061h8.516q.607 0 .94.326.335.316.335.958z"
      clipRule="evenodd"
    />
  </svg>
);
export { FolderTiny };
