// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const Folder = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M4.257 20.25q-1.362 0-1.866-.78-.507-.77-.135-2.272l1.74-7.02c.212-.86 1.104-1.559 1.99-1.559h16.056c.887 0 1.433.698 1.22 1.559l-1.74 7.02q-.372 1.503-1.235 2.273-.865.78-2.067.779z"
    />
    <path
      fill="currentColor"
      d="M20.757 7.295H6.315c-1.64 0-3.29 1.29-3.685 2.883L1.5 14.74V5.887q0-1.43.656-2.154Q2.82 3 3.996 3h2.38q.436 0 .756.063.32.064.588.218.27.144.564.407l.479.425q.353.299.664.425.31.127.765.127h7.817q1.354 0 2.051.751.627.666.697 1.879"
    />
  </svg>
);
export { Folder };
