// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const FolderTinyFilled = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M2.5 17.062v-6.86h19v6.86q0 1.296-.628 1.94-.626.654-1.748.653H5.127q-1.314 0-1.974-.652-.653-.645-.653-1.941m0-7.957V6.863q0-1.263.602-1.89.602-.628 1.707-.628h2.385q.41 0 .71.058.31.06.561.193.26.134.536.368l.51.418q.319.268.61.385.294.11.72.109h8.032q1.305 0 1.966.652.66.652.661 1.941v.636z"
    />
  </svg>
);
export { FolderTinyFilled };
