// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const FolderFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M1.802 17.434v-7.365h20.396v7.364q0 1.393-.673 2.084-.675.7-1.877.7H4.622q-1.41 0-2.12-.7-.7-.69-.7-2.084m0-8.542V6.485q0-1.356.646-2.03.647-.673 1.833-.673h2.56q.44 0 .763.063a2.1 2.1 0 0 1 .601.206q.28.144.575.396l.548.449q.341.287.656.413.315.117.772.117h8.622q1.402 0 2.11.7.71.7.71 2.084v.682z"
    />
  </IconSvg>
);
export { FolderFilled };
