// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const FormatText = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M2.854 19.405q-.504 0-.8-.277-.288-.278-.288-.762 0-.337.129-.673L6.287 5.852q.435-1.227 1.711-1.227.673 0 1.099.307.424.297.652.93l4.363 11.782a2.1 2.1 0 0 1 .139.702q0 .484-.307.772-.307.286-.831.287-.495 0-.772-.228-.277-.218-.435-.732l-1.108-3.067H5.179l-1.098 3.067q-.168.515-.445.732-.277.227-.782.227m2.889-5.867h4.52l-2.235-6.41h-.06zm9.912 8.983q-.82 0-.82-.693t.82-.692h2.097V2.854h-2.097q-.82 0-.82-.692 0-.683.82-.683h5.748q.83 0 .83.683 0 .692-.83.692h-2.058v18.282h2.058q.83 0 .83.692 0 .693-.83.693z"
    />
  </svg>
);
export { FormatText };
