// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Glass = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M15 1a1 1 0 0 1 .937.648C17.442 5.663 18 7.808 18 10a6 6 0 0 1-5 5.914V21h3a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2h3v-5.086A6 6 0 0 1 6 10c0-2.193.558-4.337 2.063-8.352l.066-.14A1 1 0 0 1 9 1zM8.128 11a4 4 0 0 0 7.744 0zm1.571-8C8.647 5.864 8.186 7.556 8.048 9h7.904c-.138-1.444-.6-3.136-1.651-6z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Glass };
