// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Glasses = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M16 4c.918 0 1.705.219 2.379.697.571.406.998.956 1.353 1.565l.149.264.042.09 2.5 6q.029.07.045.14A5 5 0 1 1 13 15a1 1 0 0 0-2 .001 5 5 0 1 1-9.469-2.243q.018-.072.046-.142l2.5-6 .042-.089c.371-.69.808-1.35 1.454-1.82C6.247 4.212 7.043 4 8 4a1 1 0 0 1 0 2c-.644 0-.997.137-1.248.32-.274.2-.533.532-.854 1.122l-1.13 2.71Q5.362 10.001 6 10a5 5 0 0 1 4.332 2.506 3 3 0 0 1 3.335 0 5 5 0 0 1 5.563-2.354L18.1 7.438c-.308-.564-.588-.903-.88-1.11C16.946 6.132 16.583 6 16 6a1 1 0 1 1 0-2M6 12a3 3 0 1 0 0 6 3 3 0 0 0 0-6m12 0a3 3 0 1 0 0 6 3 3 0 0 0 0-6"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Glasses };
