// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
/** @deprecated This icon is no longer available in the Figma source. It will be removed in a future version. */
const Globe2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1c6.075 0 11 4.925 11 11s-4.925 11-11 11S1 18.075 1 12 5.925 1 12 1M3.057 13a9.005 9.005 0 0 0 6.609 7.692A15.5 15.5 0 0 1 7.033 13zm13.91 0a15.5 15.5 0 0 1-2.634 7.692A9.005 9.005 0 0 0 20.943 13zM9.04 13A13.5 13.5 0 0 0 12 20.483 13.5 13.5 0 0 0 14.96 13zm.626-9.693A9.01 9.01 0 0 0 3.056 11h3.977a15.5 15.5 0 0 1 2.633-7.693M12 3.516A13.5 13.5 0 0 0 9.04 11h5.92A13.5 13.5 0 0 0 12 3.516m2.333-.21A15.5 15.5 0 0 1 16.967 11h3.976a9.005 9.005 0 0 0-6.61-7.693"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Globe2 };
