// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const GlobeLock = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1a1 1 0 0 1 .725 1.69A13.5 13.5 0 0 0 9.037 11H10.5a1 1 0 1 1 0 2H9.04a13.5 13.5 0 0 0 2.959 7.482 13.5 13.5 0 0 0 2.709-5.689 1 1 0 0 1 1.957.414 15.5 15.5 0 0 1-2.334 5.484 9 9 0 0 0 6.258-5.99 1 1 0 1 1 1.907.599 11 11 0 0 1-10.473 7.698L12 23l-.016-.001a11 11 0 0 1-8.848-4.49 11 11 0 0 1-2.132-6.424 1 1 0 0 1 0-.187A11 11 0 0 1 12 1M3.059 13a9 9 0 0 0 6.606 7.69A15.5 15.5 0 0 1 7.035 13zm6.606-9.69A9 9 0 0 0 3.06 11h3.974a15.5 15.5 0 0 1 2.631-7.69"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M18 1a3 3 0 0 1 3 3v1a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2V4a3 3 0 0 1 3-3m-3 9h6V7h-6zm3-7a1 1 0 0 0-1 1v1h2V4a1 1 0 0 0-1-1"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { GlobeLock };
