// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Hashtag = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M16.11 2.006a1 1 0 0 1 .884 1.104L16.451 8H20a1 1 0 0 1 0 2h-3.771l-.445 4H20a1 1 0 0 1 0 2h-4.438l-.568 5.11a1 1 0 0 1-1.988-.22l.543-4.89H9.562l-.568 5.11a1 1 0 0 1-1.988-.22L7.549 16H4a1 1 0 1 1 0-2h3.771l.445-4H4a1 1 0 0 1 0-2h4.438l.568-5.11a1 1 0 0 1 1.988.22L10.451 8h3.987l.568-5.11a1 1 0 0 1 1.104-.884M10.23 10l-.445 4h3.987l.445-4z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Hashtag };
