// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Heading2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12 5a1 1 0 0 1 1 1v12a1 1 0 1 1-2 0v-5H5v5a1 1 0 1 1-2 0V6a1 1 0 0 1 2 0v5h6V6a1 1 0 0 1 1-1M16.4 10.2c1.217-.912 2.555-1.145 3.666-.774C21.166 9.792 22 10.76 22 12c0 1.016-.355 1.762-.903 2.333-.485.505-1.133.869-1.567 1.14-.487.304-.843.563-1.096.912-.117.16-.224.357-.303.615H21a1 1 0 0 1 0 2h-4a1 1 0 0 1-1-1c0-1.182.3-2.082.816-2.791.497-.683 1.14-1.112 1.654-1.433.566-.354.918-.552 1.183-.828.202-.21.347-.464.347-.948 0-.261-.166-.543-.566-.677-.389-.13-1.052-.11-1.834.477a1 1 0 1 1-1.2-1.6"
    />
  </IconSvg>
);
export { Heading2 };
