// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Heading1 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12 5a1 1 0 0 1 1 1v12a1 1 0 1 1-2 0v-5H5v5a1 1 0 1 1-2 0V6a1 1 0 0 1 2 0v5h6V6a1 1 0 0 1 1-1M19.445 9.168A1 1 0 0 1 21 10v8a1 1 0 1 1-2 0v-6.132l-1.445.964a1 1 0 1 1-1.11-1.664z"
    />
  </IconSvg>
);
export { Heading1 };
