// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Hourglass = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M19 1a1 1 0 1 1 0 2h-1v3.172a3 3 0 0 1-.68 1.901l-.199.22L13.414 12l3.707 3.707.2.22A3 3 0 0 1 18 17.828V21h1a1 1 0 1 1 0 2H5a1 1 0 1 1 0-2h1v-3.172a3 3 0 0 1 .879-2.121L10.586 12 6.879 8.293A3 3 0 0 1 6 6.172V3H5a1 1 0 0 1 0-2zM8.293 17.121a1 1 0 0 0-.293.707V21h8v-3.172a1 1 0 0 0-.293-.707L12 13.414zM8 3v3.172l.005.099a1 1 0 0 0 .288.608L12 10.586l3.707-3.707a1 1 0 0 0 .288-.608l.005-.1V3z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Hourglass };
