// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Icon14CircleFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M14.824 9.87a.2.2 0 0 1 .358.122v2.377a.2.2 0 0 1-.2.2h-1.851a.2.2 0 0 1-.158-.323z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2M8.015 7.309a.2.2 0 0 0-.1.026l-2.67 1.538a.2.2 0 0 0-.064.288l.669.957a.2.2 0 0 0 .261.06l1.485-.833a.2.2 0 0 1 .298.174v6.973c0 .11.09.2.2.2h1.408a.2.2 0 0 0 .2-.2V7.508a.2.2 0 0 0-.2-.2zm6.972.013a.2.2 0 0 0-.159.078l-3.915 5.115a.2.2 0 0 0-.042.122v1.365c0 .11.09.2.2.2h3.911c.11 0 .2.09.2.2v2.09c0 .11.09.2.2.2h1.408a.2.2 0 0 0 .2-.2v-2.09c0-.11.09-.2.2-.2h.55a.2.2 0 0 0 .2-.2v-1.233a.2.2 0 0 0-.2-.2h-.55a.2.2 0 0 1-.2-.2V7.521a.2.2 0 0 0-.2-.199z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Icon14CircleFilled };
