// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Icon11CircleFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2M9.145 7.309a.2.2 0 0 0-.1.026l-2.67 1.538a.2.2 0 0 0-.064.288l.668.957a.2.2 0 0 0 .262.06l1.485-.833a.2.2 0 0 1 .297.174v6.973c0 .11.09.2.2.2h1.408a.2.2 0 0 0 .2-.2V7.508a.2.2 0 0 0-.2-.2zm5.32 0a.2.2 0 0 0-.1.026l-2.67 1.538a.2.2 0 0 0-.063.288l.668.957a.2.2 0 0 0 .261.06l1.486-.833a.2.2 0 0 1 .298.174v6.973c0 .11.09.2.2.2h1.406a.2.2 0 0 0 .2-.2V7.508a.2.2 0 0 0-.2-.2z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Icon11CircleFilled };
