// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Icon1CircleFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2m-.249 5.145a.2.2 0 0 0-.1.026L8.88 8.767a.2.2 0 0 0-.064.288l.7 1.003a.2.2 0 0 0 .262.06l1.552-.873a.2.2 0 0 1 .298.175v7.235c0 .11.09.2.2.2h1.47a.2.2 0 0 0 .201-.2v-9.31a.2.2 0 0 0-.2-.2z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Icon1CircleFilled };
