// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Icon7CircleFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2M8.927 7.151a.2.2 0 0 0-.2.2v1.29c0 .11.09.2.2.2h4.428a.2.2 0 0 1 .17.305l-4.502 7.399a.2.2 0 0 0 .171.304h1.69a.2.2 0 0 0 .174-.099l4.61-7.861a.2.2 0 0 0 .028-.102V7.352a.2.2 0 0 0-.2-.2z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Icon7CircleFilled };
