// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Icon2CircleFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2m.059 4.525q-1.275 0-2.19.582a4.9 4.9 0 0 0-1.413 1.41.195.195 0 0 0 .063.275l1.177.718a.206.206 0 0 0 .28-.067q.343-.531.738-.867.471-.388 1.164-.388.387 0 .679.153.304.152.471.429.18.276.18.678 0 .305-.097.569a2 2 0 0 1-.25.499 3.4 3.4 0 0 1-.387.484q-.222.25-.5.541l-3.25 3.21a.2.2 0 0 0-.06.143V16.3c0 .11.09.2.2.2h6.291a.2.2 0 0 0 .2-.2v-1.29a.2.2 0 0 0-.2-.2h-3.722a.2.2 0 0 1-.14-.344l1.984-1.914q.486-.47.887-.97.415-.513.679-1.08a2.9 2.9 0 0 0 .262-1.233q0-.832-.415-1.44a2.6 2.6 0 0 0-1.094-.957 3.34 3.34 0 0 0-1.537-.347"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Icon2CircleFilled };
