// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Icon4CircleFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M11.865 9.546a.2.2 0 0 1 .359.123v2.487a.2.2 0 0 1-.2.2h-1.939a.2.2 0 0 1-.158-.323z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2m.018 4.926a.2.2 0 0 0-.16.078l-4.054 5.299a.2.2 0 0 0-.041.12v1.423c0 .11.089.2.199.2h4.061c.11 0 .2.09.2.2v2.177c0 .11.09.2.2.2h1.47a.2.2 0 0 0 .2-.2v-2.177a.2.2 0 0 1 .2-.2h.584a.2.2 0 0 0 .2-.2v-1.29a.2.2 0 0 0-.2-.2h-.584a.2.2 0 0 1-.2-.2v-5.03a.2.2 0 0 0-.2-.2z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Icon4CircleFilled };
