// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Icon17CircleFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2M8.415 7.309a.2.2 0 0 0-.1.026l-2.67 1.538a.2.2 0 0 0-.064.288l.669.957a.2.2 0 0 0 .262.06l1.484-.833a.2.2 0 0 1 .299.174v6.973c0 .11.089.2.2.2h1.407a.2.2 0 0 0 .2-.2V7.508a.2.2 0 0 0-.2-.2zm3.417.013a.2.2 0 0 0-.2.2v1.233c.001.11.09.2.2.2h4.26a.2.2 0 0 1 .17.304l-4.337 7.129a.2.2 0 0 0 .17.304h1.618a.2.2 0 0 0 .173-.1l4.452-7.591a.2.2 0 0 0 .028-.1V7.52a.2.2 0 0 0-.2-.199z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Icon17CircleFilled };
