// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ImageSpark = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12.5 2a1 1 0 1 1 0 2H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h.586l8.793-8.793a3 3 0 0 1 4.242 0L20 12.585V11.5a1 1 0 1 1 2 0V19a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3zm4 10.328a1 1 0 0 0-.707.293L8.414 20H19a1 1 0 0 0 1-1v-3.586l-2.793-2.793a1 1 0 0 0-.707-.293"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M9 6a3 3 0 1 1 0 6 3 3 0 0 1 0-6m0 2a1 1 0 1 0 0 2 1 1 0 0 0 0-2"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M19.5 0a1 1 0 0 1 .948.684l.717 2.15 2.151.718a1 1 0 0 1 0 1.896l-2.151.717-.717 2.151a1 1 0 0 1-1.896 0l-.718-2.151-2.15-.717a1 1 0 0 1 0-1.896l2.15-.718.718-2.15.061-.147A1 1 0 0 1 19.5 0"
    />
  </IconSvg>
);
export { ImageSpark };
