// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Incognito = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M17 14a4 4 0 1 1-3.995 4.206L13 18a1 1 0 0 0-2 0l-.005.206a4 4 0 1 1-.793-2.604A3 3 0 0 1 12 15c.652 0 1.28.216 1.797.602A4 4 0 0 1 17 14M7 16a2 2 0 1 0 0 4 2 2 0 0 0 0-4m10 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4M14.925 2a3 3 0 0 1 2.854 1.866l.056.149.008.026L19.733 10H22a1 1 0 1 1 0 2H2a1 1 0 1 1 0-2h2.244l1.368-4.816A3 3 0 0 1 8.5 3H12c.149 0 .296-.033.43-.097l1.277-.611c.38-.182.796-.281 1.218-.292m.05 1.999q-.16.005-.308.058l-.098.04-1.276.61a3 3 0 0 1-1.126.288L12 5H8.5a1 1 0 0 0-.963.728L6.323 10h11.312l-1.69-5.33-.04-.097a1 1 0 0 0-.93-.574"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Incognito };
