// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
/** @deprecated This icon is no longer available in the Figma source. It will be removed in a future version. */
const Key2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path fill="currentColor" d="M16.5 6a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3" />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M11.553 2.108a7.502 7.502 0 0 1 10.339 10.339 7.5 7.5 0 0 1-8.207 3.28l-.392.393a3 3 0 0 1-2.121.88H11v1a2 2 0 0 1-2 2H8v1a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-2.172c0-.796.316-1.56.879-2.122l6.392-6.392a7.5 7.5 0 0 1 3.282-8.206m4.603.888A5.5 5.5 0 0 0 10.35 6.64a5.5 5.5 0 0 0-.004 3.632c.126.362.033.765-.238 1.036L3.293 18.12a1 1 0 0 0-.293.707V21h3v-1a2 2 0 0 1 2-2h1v-1a2 2 0 0 1 2-2h.172l.098-.005a1 1 0 0 0 .609-.288l.814-.814.108-.093a1 1 0 0 1 .928-.143 5.502 5.502 0 0 0 7.275-5.813 5.5 5.5 0 0 0-4.848-4.847"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Key2 };
