// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Language = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M17 11a1 1 0 0 1 .895.553l5 10a1 1 0 0 1-1.79.894L19.383 19h-4.764l-1.723 3.447a1 1 0 0 1-1.79-.894l5-10 .072-.121A1 1 0 0 1 17 11m-1.382 6h2.764L17 14.236z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M14 4a1 1 0 1 1 0 2h-1.465c-.575.863-.992 1.613-1.708 2.5-.717.887-1.913 2-1.913 2l2.793 2.793a1 1 0 1 1-1.414 1.414L7.5 11.914l-2.793 2.793a1 1 0 1 1-1.414-1.414L6.086 10.5 4.293 8.707a1 1 0 1 1 1.414-1.414L7.5 9.086l.564-.564c.77-.77 1.463-1.615 2.068-2.522H2a1 1 0 0 1 0-2zM8 1a1 1 0 0 1 0 2H7a1 1 0 0 1 0-2z"
    />
  </IconSvg>
);
export { Language };
