// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Leave = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M19 2a3 3 0 0 1 3 3v1a1 1 0 1 1-2 0V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-1a1 1 0 1 1 2 0v1a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3z"
    />
    <path
      fill="currentColor"
      d="M15.293 7.293a1 1 0 0 1 1.414 0l4 4a1 1 0 0 1 .25.414l.015.062q.027.111.028.231-.001.084-.016.165a.991.991 0 0 1-.202.455 1 1 0 0 1-.075.087l-4 4a1 1 0 1 1-1.414-1.414L17.586 13H9a1 1 0 1 1 0-2h8.586l-2.293-2.293a1 1 0 0 1 0-1.414"
    />
  </IconSvg>
);
export { Leave };
