// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Lock = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1a6 6 0 0 1 6 6v3h1a3 3 0 0 1 3 3v7a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3v-7a3 3 0 0 1 3-3h1V7a6 6 0 0 1 6-6M5 12a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-7a1 1 0 0 0-1-1zm7-9a4 4 0 0 0-4 4v3h8V7a4 4 0 0 0-4-4"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Lock };
