// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Login = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M19 2a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3h-4a1 1 0 1 1 0-2h4a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1h-4a1 1 0 1 1 0-2z"
    />
    <path
      fill="currentColor"
      d="M9.293 6.293a1 1 0 0 1 1.414 0l5 5a1 1 0 0 1 .25.414l.015.062q.027.111.028.231-.001.084-.016.165a.991.991 0 0 1-.202.455 1 1 0 0 1-.075.087l-5 5a1 1 0 1 1-1.414-1.414L12.586 13H3a1 1 0 1 1 0-2h9.586L9.293 7.707a1 1 0 0 1 0-1.414"
    />
  </IconSvg>
);
export { Login };
