// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Measure = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 2a3 3 0 0 1 3 3c0 .753-.28 1.438-.738 1.965l1.53 2.726a1 1 0 0 1-1.745.979l-1.523-2.717a3 3 0 0 1-1.041.002L8.489 13.28l.029.014a9 9 0 0 0 9.904-1.993 1 1 0 1 1 1.427 1.4A11 11 0 0 1 12 15.994c-1.46 0-2.908-.291-4.256-.856q-.12-.053-.24-.109L3.871 21.49a1.001 1.001 0 0 1-1.744-.98l3.633-6.46a11 11 0 0 1-1.61-1.35 1 1 0 0 1 1.428-1.4c.36.366.752.698 1.167.997L9.742 6.97A3 3 0 0 1 8.999 5a3 3 0 0 1 3-3m0 2a1 1 0 0 0-.515 1.855l.024.013.028.018A1 1 0 1 0 12 4"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M18.349 16.29a1 1 0 0 1 1.361.38l2.16 3.84a1 1 0 1 1-1.743.98l-2.159-3.84a1 1 0 0 1 .38-1.36"
    />
  </IconSvg>
);
export { Measure };
