// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Megaphone = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M19.82 2.008A2 2 0 0 1 22 4v12a2 2 0 0 1-2.18 1.992 2 2 0 0 1-1.02-.393l-.02-.015a12 12 0 0 0-7.707-2.585A7 7 0 0 0 12.4 18.2a3 3 0 0 1-4.8 3.6A13 13 0 0 1 5.04 15H5a3 3 0 0 1-3-3V8a3 3 0 0 1 3-3h6.025a12 12 0 0 0 7.754-2.584l.02-.016c.298-.223.652-.36 1.021-.392M7.048 15A11 11 0 0 0 9.2 20.6a1 1 0 1 0 1.6-1.2A9 9 0 0 1 9.058 15zM20 4a14 14 0 0 1-8.413 3.002L10.975 7H9v6h1.975A14 14 0 0 1 20 16zM5 7a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h2V7z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Megaphone };
