// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const MicFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M19 9a1 1 0 0 1 1 1v2a7.997 7.997 0 0 1-7 7.935V22a1 1 0 1 1-2 0v-2.065A7.997 7.997 0 0 1 4 12v-2a1 1 0 1 1 2 0v2a6 6 0 0 0 12 0v-2a1 1 0 0 1 1-1"
    />
    <path
      fill="currentColor"
      d="M12 1a4 4 0 0 1 4 4v7a4 4 0 0 1-8 0V5a4 4 0 0 1 4-4"
    />
  </IconSvg>
);
export { MicFilled };
