// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const MicOffWarning = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M15.463 8.538Q16.926 10 19 10q2.075 0 3.538-1.463Q24 7.076 24 5t-1.462-3.537Q21.074 0 19 0q-2.075 0-3.537 1.463Q14 2.925 14 5t1.463 3.537m3.887-.688a.48.48 0 0 1-.7 0 .48.48 0 0 1 0-.7.48.48 0 0 1 .7 0 .48.48 0 0 1 0 .7M19.5 6h-1V2h1zM12 2q.327 0 .629.06a6.7 6.7 0 0 0-.563 1.942L12 4a.97.97 0 0 0-.713.287A.97.97 0 0 0 11 5v3.15l-2-2V5q0-1.25.875-2.125A2.9 2.9 0 0 1 12 2m1 8.15V8.631a7.2 7.2 0 0 0 1.048 1.32q.452.453.952.806V11q0 .275-.063.5-.062.225-.137.45zm3.95 1.558a7.1 7.1 0 0 0 1.98.292 6.4 6.4 0 0 1-.255 1.088 7.3 7.3 0 0 1-.925 1.862L16.3 13.5a4.8 4.8 0 0 0 .65-1.792M11 21v-3.075q-2.6-.35-4.3-2.325T5 11h2q0 2.075 1.437 3.537Q9.875 16 12 16q.561 0 1.085-.115L1.4 4.2l1.4-1.4L15 15l1.425 1.425L21.2 21.2l-1.4 1.4-5.127-5.127a6.2 6.2 0 0 1-1.673.452V21z"
      clipRule="evenodd"
    />
  </svg>
);
export { MicOffWarning };
