// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Minimize = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M20.086 2.5A1 1 0 1 1 21.5 3.914l-5.293 5.293h3.586a1 1 0 1 1 0 2h-6a1 1 0 0 1-1-1v-6a1 1 0 1 1 2 0v3.586zm-8.379 16.793a1 1 0 0 1-2 0v-3.586L4.414 21A1 1 0 1 1 3 19.586l5.293-5.293H4.707a1 1 0 0 1 0-2h6a1 1 0 0 1 1 1z"
    />
  </IconSvg>
);
export { Minimize };
