// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const MinusFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12 22a9.65 9.65 0 0 1-3.883-.786 10.1 10.1 0 0 1-3.193-2.157 10.1 10.1 0 0 1-2.147-3.174A9.75 9.75 0 0 1 2 12q0-2.07.777-3.883a10.097 10.097 0 0 1 5.34-5.34A9.75 9.75 0 0 1 12 2q2.07 0 3.883.777a10 10 0 0 1 3.183 2.157q1.371 1.371 2.148 3.183A9.65 9.65 0 0 1 22 12a9.65 9.65 0 0 1-.786 3.883 10.1 10.1 0 0 1-2.148 3.174 10 10 0 0 1-3.183 2.157A9.65 9.65 0 0 1 12 22m-3.7-8.964h7.4q.471 0 .777-.279.307-.277.307-.738 0-.47-.297-.748t-.786-.278H8.299q-.48 0-.786.278-.297.279-.297.748 0 .46.307.738.306.279.776.279"
    />
  </IconSvg>
);
export { MinusFilled };
