// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Minus = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M5.405 13.023a.94.94 0 0 1-.49-.137 1.2 1.2 0 0 1-.373-.372.97.97 0 0 1-.146-.518q0-.273.146-.51.145-.236.373-.372a.94.94 0 0 1 .49-.137h13.19q.263 0 .49.137a1 1 0 0 1 .373.372.96.96 0 0 1 .146.51.97.97 0 0 1-.146.518q-.135.226-.373.372a.94.94 0 0 1-.49.137z"
    />
  </IconSvg>
);
export { Minus };
