// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const NumberedList = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M3.943 14.063A2.5 2.5 0 0 1 7 16.5c0 .684-.285 1.245-.606 1.672-.236.313-.52.59-.785.828H6.5a1 1 0 0 1 0 2H3.4a1 1 0 0 1-1-1c0-.672.422-1.168.688-1.442.288-.299.68-.612.965-.854.32-.272.57-.506.742-.734.166-.22.205-.367.205-.47a.5.5 0 0 0-.866-.34 1 1 0 0 1-1.467-1.36 2.5 2.5 0 0 1 1.276-.738M21 18a1 1 0 1 1 0 2H11a1 1 0 1 1 0-2zM21 11a1 1 0 1 1 0 2H11a1 1 0 1 1 0-2zM5 3a1 1 0 0 1 1 1v4a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2V5a1 1 0 0 1 0-2zM21 4a1 1 0 1 1 0 2H11a1 1 0 1 1 0-2z"
    />
  </IconSvg>
);
export { NumberedList };
