// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const Pain = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M20.77 3.518c-1.134-1.134-3.533-1.419-6.23-.79A1.61 1.61 0 0 0 13.378 4.8l.182.546a.8.8 0 1 1-1.518.507l-.323-.967a.92.92 0 0 0-1.33-.504q-.2.113-.398.234c-.97.59-1.422 1.758-1.064 2.834l.632 1.897a.8.8 0 1 1-1.518.506l-.617-1.847a.705.705 0 0 0-1.199-.24q-.31.357-.595.728a3.24 3.24 0 0 0-.59 2.762l.537 2.15a.8.8 0 0 1-1.552.388l-.448-1.793c-1.567 3.645-1.54 7.287-.058 8.77 1.229 1.228 2.472.977 3.45-.001L20.769 6.968c.978-.978 1.23-2.22 0-3.45"
    />
  </svg>
);
export { Pain };
