// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const Pancake = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M10.8 2.4a2 2 0 0 0-1.598 3.2H4.4a1.2 1.2 0 0 0 0 2.4h4.4a1.6 1.6 0 0 1 1.6 1.6v.8a.8.8 0 1 0 1.6 0V9.2a1.2 1.2 0 0 1 2.4 0v6a.8.8 0 1 0 1.6 0v-4.8A2.4 2.4 0 0 1 18.4 8h1.2a1.2 1.2 0 0 0 0-2.4h-4.615a1.6 1.6 0 0 0-2.378-2.055A2 2 0 0 0 10.8 2.4M3.6 9.6a1.2 1.2 0 1 0 0 2.4h5.824a2.38 2.38 0 0 1-.624-1.6v-.8zm14.8 0c-.44 0-.8.36-.8.8V12h2a1.2 1.2 0 1 0 0-2.4zm-14 4a1.2 1.2 0 1 0 0 2.4h8.547a2.4 2.4 0 0 1-.147-.8v-1.6zm13.2 0v1.6c0 .282-.057.549-.147.8H21.2a1.2 1.2 0 1 0 0-2.4zm-14 4a1.201 1.201 0 1 0 0 2.4h16a1.2 1.2 0 1 0 0-2.4z"
    />
  </svg>
);
export { Pancake };
