// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Phone = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M8 4a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1 17 17 0 0 0 17 17 1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1h-3a1 1 0 0 0-.8.4l-.005.007-.355.463a2 2 0 0 1-2.425.607l-.023-.011a15 15 0 0 1-6.849-6.84l-.002-.004a2 2 0 0 1 .584-2.466l.007-.005L7.6 7.8A1 1 0 0 0 8 7zm2 3a3 3 0 0 1-1.2 2.4l-.462.345a13 13 0 0 0 5.911 5.913l.35-.458.11-.136A3 3 0 0 1 17 14h3a3 3 0 0 1 3 3v3a3 3 0 0 1-3 3A19 19 0 0 1 1 4a3 3 0 0 1 3-3h3a3 3 0 0 1 3 3z"
    />
  </IconSvg>
);
export { Phone };
