// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const PinFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M16 2a2 2 0 0 1 .197 3.99l-.296.015A1 1 0 0 0 15 7v3.76a2 2 0 0 0 1.11 1.79l1.78.9A2 2 0 0 1 19 15.24V16a1 1 0 0 1-1 1h-5v5a1 1 0 1 1-2 0v-5H6a1 1 0 0 1-1-1v-.76a2 2 0 0 1 1.11-1.79l1.78-.9A2 2 0 0 0 9 10.76V7a1 1 0 0 0-.901-.995l-.296-.015A2 2 0 0 1 8 2z"
    />
  </IconSvg>
);
export { PinFilled };
