// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const PinOff = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M1.293 1.293a1 1 0 0 1 1.414 0l20 20a1 1 0 0 1-1.414 1.414L16.586 18H13v4a1 1 0 1 1-2 0v-4H6a2 2 0 0 1-2-2v-.76l.008-.209a3 3 0 0 1 1.657-2.476l1.773-.898.007-.003a1 1 0 0 0 .545-.756L8 10.76V9.414L1.293 2.707a1 1 0 0 1 0-1.414m8.645 10.06c-.07.348-.2.682-.388.987a3 3 0 0 1-1.21 1.101v.001l-1.779.9-.006.004A1 1 0 0 0 6 15.24V16h8.586z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M16 1a3.001 3.001 0 0 1 0 6v2.34a1 1 0 0 1-2 0V7a2 2 0 0 1 2-2 1.002 1.002 0 0 0 .707-1.707A1 1 0 0 0 16 3H7.89a1 1 0 0 1 0-2z"
    />
  </IconSvg>
);
export { PinOff };
