// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const Pizza = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M21.6 14.698C21.6 7.906 16.093 2.4 9.3 2.4L2.473 20.153c-.33.86.514 1.704 1.374 1.373l4.666-1.794a.8.8 0 0 1 1.087.746v.322a.8.8 0 0 0 1.6 0v-1.278a1.2 1.2 0 1 1 2.4 0V21.6a.8.8 0 0 0 1.6 0v-2.792a2.4 2.4 0 0 1 1.538-2.24zM7.2 17.6a1.6 1.6 0 1 1-.001-3.2 1.6 1.6 0 0 1 0 3.2m2.8-7.2A1.2 1.2 0 1 1 10 8a1.2 1.2 0 0 1 0 2.4m2.8 1.6a2.4 2.4 0 1 1 4.8 0 2.4 2.4 0 0 1-4.8 0"
    />
  </svg>
);
export { Pizza };
