// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Play2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M7.01 2a3 3 0 0 1 1.502.409l11.994 6.996A3 3 0 0 1 22 11.998a3 3 0 0 1-1.323 2.49l-.166.104-12 7A3.002 3.002 0 0 1 4 19V5a3 3 0 0 1 3.01-3M6 19a1 1 0 0 0 1.504.865l12-7v-.001a1 1 0 0 0-.001-1.729H19.5L7.504 4.135a1 1 0 0 0-1.37.363 1 1 0 0 0-.134.5z"
    />
  </IconSvg>
);
export { Play2 };
