// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Play = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M7.64 3.5c.393.001.779.107 1.119.305l10.732 6.26a2.24 2.24 0 0 1 1.115 1.933 2.24 2.24 0 0 1-.987 1.856l-.124.078L8.76 20.195a2.236 2.236 0 0 1-3.364-1.933V5.737A2.24 2.24 0 0 1 7.64 3.5"
    />
  </IconSvg>
);
export { Play };
