// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const PlugOn = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M15.5 2A4.5 4.5 0 0 1 20 6.5V13a3 3 0 0 1 3 3v2a2 2 0 0 1-1 1.73V21a1 1 0 1 1-2 0v-1h-2v1a1 1 0 1 1-2 0v-1.27A2 2 0 0 1 15 18v-2a3 3 0 0 1 3-3V6.5a2.5 2.5 0 0 0-5 0v11a4.5 4.5 0 0 1-9 0V11a3 3 0 0 1-3-3V6a2 2 0 0 1 1-1.73V3a1 1 0 0 1 2 0v1h2V3a1 1 0 0 1 2 0v1.27q.226.129.414.316A2 2 0 0 1 9 6v2a3 3 0 0 1-3 3v6.5a2.5 2.5 0 0 0 5 0v-11A4.5 4.5 0 0 1 15.5 2M18 15a1 1 0 0 0-1 1v2h4v-2a1 1 0 0 0-1-1zM3 8a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1V6H3z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { PlugOn };
