// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Quote = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M8 2a3 3 0 0 1 3 3v10a7 7 0 0 1-7 7 2 2 0 0 1-2-2v-2a2 2 0 0 1 1.803-1.99l.296-.015A1 1 0 0 0 5 15v-1a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3zM5 4a1 1 0 0 0-1 1v6a1 1 0 0 0 .901.995l.296.015A2 2 0 0 1 7 14v1a3 3 0 0 1-3 3v2a5 5 0 0 0 5-5V5a1 1 0 0 0-1-1zM19 2a3 3 0 0 1 3 3v10a7 7 0 0 1-7 7 2 2 0 0 1-2-2v-2a2 2 0 0 1 1.803-1.99l.296-.015A1 1 0 0 0 16 15v-1a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3zm-3 2a1 1 0 0 0-1 1v6a1 1 0 0 0 .901.995l.296.015A2 2 0 0 1 18 14v1a3 3 0 0 1-3 3v2a5 5 0 0 0 5-5V5a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Quote };
