// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Record = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12.005 8q1.104 0 2.003.542a4.1 4.1 0 0 1 1.45 1.45A3.86 3.86 0 0 1 16 12.005a3.86 3.86 0 0 1-.542 2.013q-.54.899-1.45 1.44-.9.542-2.003.542a3.86 3.86 0 0 1-2.013-.542 4.14 4.14 0 0 1-1.45-1.44A3.86 3.86 0 0 1 8 12.005q0-1.104.542-2.013a4.1 4.1 0 0 1 1.45-1.45A3.86 3.86 0 0 1 12.005 8"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 1c6.075 0 11 4.925 11 11s-4.925 11-11 11S1 18.075 1 12 5.925 1 12 1m0 2a9 9 0 1 0 0 18 9 9 0 0 0 0-18"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Record };
