// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Reply = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M4 3a1 1 0 0 1 1 1c0 1.882.001 3.236.084 4.3.082 1.055.24 1.742.51 2.303a6 6 0 0 0 2.802 2.803c.562.27 1.25.428 2.303.51 1.065.083 2.42.084 4.301.084h2.586l-3.293-3.293a1 1 0 1 1 1.414-1.414l5 5a1 1 0 0 1 .25.414l.015.062q.027.111.028.231a1 1 0 0 1-.293.707l-5 5a1 1 0 1 1-1.414-1.414L17.586 16H15c-1.85 0-3.295 0-4.456-.09-1.171-.091-2.137-.28-3.015-.702a8 8 0 0 1-3.737-3.737c-.423-.878-.61-1.844-.702-3.015C3 7.296 3 5.85 3 4a1 1 0 0 1 1-1"
    />
  </IconSvg>
);
export { Reply };
