// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Retry = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12 2A10 10 0 1 1 2 12a1 1 0 1 1 2 0 8 8 0 1 0 8.002-8 8.75 8.75 0 0 0-6.047 2.459L5.415 7H8a1 1 0 0 1 0 2H3q-.085-.001-.166-.016-.015-.001-.031-.005l-.034-.007-.062-.016a1 1 0 0 1-.205-.09 1 1 0 0 1-.382-.391l-.02-.042a1 1 0 0 1-.057-.141A1 1 0 0 1 2 8V3a1 1 0 0 1 2 0v2.586l.553-.553.393-.363A10.75 10.75 0 0 1 11.996 2z"
    />
  </IconSvg>
);
export { Retry };
