// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Scale = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 2a1 1 0 0 1 1 1v1.385A16 16 0 0 0 20 6h1a1 1 0 1 1 0 2h-.932l2.868 7.648A1 1 0 0 1 22.6 16.8a6 6 0 0 1-7.199 0 1 1 0 0 1-.337-1.152l2.911-7.764A18 18 0 0 1 13 6.58V20h4a1 1 0 1 1 0 2H7a1 1 0 0 1 0-2h4V6.581a18 18 0 0 1-4.976 1.304l2.912 7.763A1 1 0 0 1 8.6 16.8a6 6 0 0 1-7.199 0 1 1 0 0 1-.337-1.152L3.931 8H3a1 1 0 0 1 0-2h1c2.428 0 4.82-.555 7-1.615V3a1 1 0 0 1 1-1M3.224 15.581C3.774 15.853 4.38 16 5 16c.619 0 1.225-.147 1.774-.419L5 10.85zm14 0c.55.272 1.156.419 1.776.419.619 0 1.225-.147 1.774-.419L19 10.85z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Scale };
