// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const Sd = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M11.006 10.349h-3.5v1h2.498a1 1 0 0 1 1 1.002l-.002 1.651a1 1 0 0 1-1 .998H6l.008-1.382h3.5v-1H7.006a1 1 0 0 1-1-.998l-.004-1.618a1 1 0 0 1 1-1.002H11z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M17 9q.425 0 .713.287Q18 9.575 18 10v4a.97.97 0 0 1-.287.713A.97.97 0 0 1 17 15h-4V9zm-2.5 1.5v3h2v-3z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M20 4q.825 0 1.412.588Q22 5.176 22 6v12q0 .825-.588 1.412A1.93 1.93 0 0 1 20 20H4q-.824 0-1.412-.588A1.93 1.93 0 0 1 2 18V6q0-.824.588-1.412A1.93 1.93 0 0 1 4 4zM4 18h16V6H4z"
      clipRule="evenodd"
    />
  </svg>
);
export { Sd };
