// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ShareScreen = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12.02 6.001q.027 0 .053.002l.053.005q.018.002.035.006l.057.01.027.007a1 1 0 0 1 .292.126l.023.015q.078.052.147.121l3 3a1 1 0 1 1-1.414 1.414L13 9.414V13a1 1 0 1 1-2 0V9.414l-1.293 1.293a1 1 0 1 1-1.414-1.414l3-3q.094-.093.208-.16l.044-.023a1 1 0 0 1 .197-.076l.05-.013.033-.005A1 1 0 0 1 11.98 6L12 6z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M20 2a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3h-7v2h3a1 1 0 1 1 0 2H8a1 1 0 1 1 0-2h3v-2H4a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3zM4 4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { ShareScreen };
