// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Shared = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12 14a5 5 0 0 1 5 5v2a1 1 0 1 1-2 0v-2a3 3 0 0 0-3-3H6a3 3 0 0 0-3 3v2a1 1 0 1 1-2 0v-2a5 5 0 0 1 5-5zM18.032 14.88a1 1 0 0 1 1.218-.718A5 5 0 0 1 23 19V21a1 1 0 0 1-2 0v-1.999l-.01-.248a3 3 0 0 0-2.24-2.655 1 1 0 0 1-.718-1.218"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M9 2a5 5 0 1 1 0 10A5 5 0 0 1 9 2m0 2a3 3 0 1 0 0 6 3 3 0 0 0 0-6"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M15.032 2.877a1 1 0 0 1 1.219-.717 5 5 0 0 1 0 9.68 1 1 0 0 1-.502-1.936 3.001 3.001 0 0 0 0-5.808 1 1 0 0 1-.717-1.22"
    />
  </IconSvg>
);
export { Shared };
