// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Shortcut = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M18 11q.084 0 .165.015l.026.004.01.002.03.006.061.016a1 1 0 0 1 .14.057l.043.02a1 1 0 0 1 .481.587l.016.062q.027.111.028.231v6a1 1 0 1 1-2 0v-3.586l-4.293 4.293a1 1 0 1 1-1.414-1.414L15.586 13H12a1 1 0 1 1 0-2z"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M20 7a3 3 0 0 1 3 3v10a3 3 0 0 1-3 3H10a3 3 0 0 1-3-3V10a3 3 0 0 1 3-3zM10 9a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V10a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M14 1c1.652 0 3 1.348 3 3a1 1 0 1 1-2 0c0-.548-.452-1-1-1H4c-.548 0-1 .452-1 1v10c0 .548.452 1 1 1a1 1 0 1 1 0 2c-1.652 0-3-1.348-3-3V4c0-1.652 1.348-3 3-3z"
    />
  </IconSvg>
);
export { Shortcut };
