// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Show = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12 4a11.75 11.75 0 0 1 10.689 6.87l.174.401.012.033a2 2 0 0 1 0 1.392l-.012.033a11.751 11.751 0 0 1-21.726 0l-.013-.033a2 2 0 0 1 0-1.392l.013-.033A11.75 11.75 0 0 1 12 4.001m0 2a9.75 9.75 0 0 0-9 6 9.75 9.75 0 0 0 14.423 4.352A9.75 9.75 0 0 0 21 12 9.75 9.75 0 0 0 12 6"
    />
    <path
      fill="currentColor"
      d="M14 12a2 2 0 1 0-4 0 2 2 0 0 0 4 0m2 0a4 4 0 1 1-8 0 4 4 0 0 1 8 0"
    />
  </IconSvg>
);
export { Show };
