// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Sparkle2 = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <g clipPath="url(#a)">
      <path
        fill="currentColor"
        d="m21 12-5.558-1.051a3 3 0 0 1-2.39-2.39L12 2.998l-1.052 5.56a3 3 0 0 1-2.392 2.389L3 11.999l5.558 1.052a3 3 0 0 1 2.39 2.39L12 21.002l1.052-5.56a3 3 0 0 1 2.39-2.39zm2.002 0a2 2 0 0 1-1.632 1.966h-.001l-5.555 1.05a1 1 0 0 0-.798.798l-1.05 5.555a2 2 0 0 1-3.932 0l-1.051-5.555a1 1 0 0 0-.797-.798l-5.556-1.05a2 2 0 0 1-.17-3.892l.17-.04 5.556-1.051a1 1 0 0 0 .797-.797l1.05-5.556.04-.17a2.001 2.001 0 0 1 3.893.17l1.05 5.556a1 1 0 0 0 .798.797l5.555 1.05A2 2 0 0 1 23.002 12"
      />
    </g>
    <defs>
      <clipPath id="a">
        <path fill="currentColor" d="M0 0h24v24H0z" />
      </clipPath>
    </defs>
  </IconSvg>
);
export { Sparkle2 };
