// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Spotlight = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M15.017 18.602a1 1 0 0 1 1.239.683l.705 2.438a1 1 0 0 1-1.922.555l-.705-2.438a1 1 0 0 1 .683-1.238M16.127 15.513a1 1 0 0 1 1.36-.386l3.758 2.098a1 1 0 0 1-.975 1.746l-3.758-2.098a1 1 0 0 1-.385-1.36"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M8 1a1 1 0 0 1 1 1v3.897l5.964 3.115a2 2 0 0 1 .878 2.673l-3.106 6.213a2.003 2.003 0 0 1-2.7.885l-6.889-3.597-.01-.005a4 4 0 0 1-1.734-5.213l.01-.022 1.38-2.79.015-.028A4 4 0 0 1 7 5.07V2a1 1 0 0 1 1-1M7 7.129a2 2 0 0 0-2.43.943l-1.355 2.74a2.003 2.003 0 0 0 .858 2.601l6.874 3.589 3.106-6.21-.015-.008L9 8.152V9a1 1 0 1 1-2 0z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M21.832 10.92a1 1 0 0 1 .387 1.964l-3.025.597a1.001 1.001 0 0 1-.389-1.961z"
    />
  </IconSvg>
);
export { Spotlight };
