// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const StarredFilled = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      d="M5.392 21.957a1.03 1.03 0 0 1-.41-.667q-.066-.41.124-.971L7.068 14.5l-4.999-3.59q-.486-.342-.676-.713a.99.99 0 0 1-.057-.781 1 1 0 0 1 .505-.581q.37-.19.97-.19h6.123L10.8 2.837q.181-.571.476-.866a.98.98 0 0 1 .714-.305q.42 0 .714.305.305.296.486.866l1.866 5.809h6.123q.6 0 .97.19.373.19.505.58a.99.99 0 0 1-.057.781q-.19.372-.676.715l-4.998 3.59 1.961 5.817q.19.561.114.971a1 1 0 0 1-.4.666.9.9 0 0 1-.752.191q-.42-.075-.895-.419l-4.96-3.647-4.952 3.647q-.475.342-.895.419a.9.9 0 0 1-.752-.19"
    />
  </svg>
);
export { StarredFilled };
