// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Table = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M19 2a3 3 0 0 1 3 3v14a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3V5a3 3 0 0 1 3-3zM4 16v3a1 1 0 0 0 1 1h6v-4zm9 0v4h6a1 1 0 0 0 1-1v-3zm-9-2h7v-4H4zm9 0h7v-4h-7zM5 4a1 1 0 0 0-1 1v3h7V4zm8 4h7V5a1 1 0 0 0-1-1h-6z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Table };
