// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const TagAdd = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M5.5 12.5a1 1 0 0 1 1 1v2h2a1 1 0 1 1 0 2h-2v2a1 1 0 1 1-2 0v-2h-2a1 1 0 1 1 0-2h2v-2a1 1 0 0 1 1-1"
    />
    <path
      fill="currentColor"
      d="M14.429 4c.795 0 1.56.317 2.122.879l5.071 5.071a3 3 0 0 1 0 4.242l-5.071 5.072a3 3 0 0 1-2.122.878h-3.655a1 1 0 1 1 0-2h3.655c.232 0 .457-.08.634-.226l.073-.066 5.071-5.072a1 1 0 0 0 0-1.414l-5.071-5.071-.072-.066A1 1 0 0 0 14.429 6H5.123a1.43 1.43 0 0 0-1.422 1.422v3.65a1 1 0 0 1-2 0V7.414A3.427 3.427 0 0 1 5.116 4z"
    />
  </IconSvg>
);
export { TagAdd };
