// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const TextAlignStart = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M17 18a1 1 0 1 1 0 2H3a1 1 0 1 1 0-2zM15 11a1 1 0 1 1 0 2H3a1 1 0 1 1 0-2zM21 4a1 1 0 1 1 0 2H3a1 1 0 0 1 0-2z"
    />
  </IconSvg>
);
export { TextAlignStart };
