// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Thread = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M20 8a3 3 0 0 1 3 3v10.286a1.71 1.71 0 0 1-2.826 1.295l-.093-.086-2.202-2.202a1 1 0 0 0-.609-.288L17.173 20H10a3 3 0 0 1-3-3v-1a1 1 0 1 1 2 0v1a1 1 0 0 0 1 1h7.172c.795 0 1.558.316 2.121.879L21 20.586V11a1 1 0 0 0-1-1 1 1 0 1 1 0-2"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M14 1a3 3 0 0 1 3 3v6a3 3 0 0 1-3 3H6.828a1 1 0 0 0-.707.293L3.92 15.495A1.71 1.71 0 0 1 1 14.286V4a3 3 0 0 1 3-3zM4 3a1 1 0 0 0-1 1v9.586l1.707-1.707.22-.2A3 3 0 0 1 6.828 11H14a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Thread };
