// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ThumbDownFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M16.85 3c1.4 0 2.627.872 2.995 2.129l2.044 6.97c.538 1.837-.948 3.647-2.995 3.648h-4.466l.97 3.008a2.38 2.38 0 0 1-.48 2.3c-1.18 1.37-3.467 1.227-4.438-.279l-2.902-4.498a1.2 1.2 0 0 0-1.01-.531H3.606c-.887 0-1.606-.67-1.606-1.494v-9.76C2 3.67 2.72 3 3.606 3zM5.928 13.454a.5.5 0 0 0 .5.5h.65a.5.5 0 0 0 .5-.5v-8.16a.5.5 0 0 0-.5-.5h-.65a.5.5 0 0 0-.5.5z"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { ThumbDownFilled };
