// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const ThumbDown = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M16.85 3c1.4 0 2.627.872 2.995 2.129l2.044 6.97c.538 1.837-.948 3.647-2.995 3.648h-4.466l.97 3.008a2.38 2.38 0 0 1-.48 2.3c-1.18 1.37-3.467 1.227-4.438-.279l-2.902-4.498a1.2 1.2 0 0 0-1.01-.531H3.606c-.887 0-1.606-.67-1.606-1.494v-9.76C2 3.67 2.72 3 3.606 3zM7.674 14.143a3.06 3.06 0 0 1 1.557 1.213l2.9 4.498c.281.435.943.476 1.283.08l.056-.072a.69.69 0 0 0 .082-.591l-1.093-3.394c-.31-.959.462-1.924 1.537-1.924h4.898c.776 0 1.34-.686 1.135-1.382L17.986 5.6c-.14-.477-.605-.808-1.136-.808H7.674zm-3.746-.19h1.819v-9.16h-1.82z"
      clipRule="evenodd"
    />
  </svg>
);
export { ThumbDown };
