// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const ThumbUp = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M10.48 3.315a2.71 2.71 0 0 1 4.918 2.173l-.97 3.235h4.466a3.104 3.104 0 0 1 2.995 3.92l-2.044 7.493a3.105 3.105 0 0 1-2.994 2.289H3.606c-.887 0-1.606-.72-1.606-1.606v-10.49c0-.887.72-1.606 1.606-1.606h2.962c.414 0 .797-.217 1.01-.572zm2.934.906a.783.783 0 0 0-1.282.085L9.23 9.142a3.1 3.1 0 0 1-1.557 1.303v10.053h9.176c.531 0 .996-.357 1.136-.869l2.043-7.493a1.177 1.177 0 0 0-1.135-1.486h-4.897a1.606 1.606 0 0 1-1.538-2.068l1.093-3.647a.78.78 0 0 0-.138-.714M3.928 10.65v9.848h1.819V10.65z"
      clipRule="evenodd"
    />
  </svg>
);
export { ThumbUp };
