// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const ThumbUpFilled = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M10.48 3.315a2.71 2.71 0 0 1 4.918 2.173l-.97 3.235h4.466a3.104 3.104 0 0 1 2.995 3.92l-2.044 7.493a3.105 3.105 0 0 1-2.994 2.289H3.606c-.887 0-1.606-.72-1.606-1.606v-10.49c0-.887.72-1.606 1.606-1.606h2.962c.414 0 .797-.217 1.01-.572zM6.428 10.65a.5.5 0 0 0-.5.5v8.848a.5.5 0 0 0 .5.5H7a.5.5 0 0 0 .5-.5V11.15a.5.5 0 0 0-.5-.5z"
      clipRule="evenodd"
    />
  </svg>
);
export { ThumbUpFilled };
