// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const ToggleList = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M2.293 13.293a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 0 1-1.414-1.414L4.586 17l-2.293-2.293a1 1 0 0 1 0-1.414M21 18a1 1 0 0 1 0 2H10a1 1 0 0 1 0-2zM21 11a1 1 0 0 1 0 2H10a1 1 0 0 1 0-2zM2.293 3.293a1 1 0 0 1 1.414 0l3 3a1 1 0 0 1 0 1.414l-3 3a1 1 0 0 1-1.414-1.414L4.586 7 2.293 4.707a1 1 0 0 1 0-1.414M21 4a1 1 0 0 1 0 2H10a1 1 0 0 1 0-2z"
    />
  </IconSvg>
);
export { ToggleList };
