// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Upload = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M21 14a1 1 0 0 1 1 1v4a3 3 0 0 1-3 3H5a3 3 0 0 1-3-3v-4a1 1 0 1 1 2 0v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1"
    />
    <path
      fill="currentColor"
      d="M12.02 2.001q.027 0 .053.002a1 1 0 0 1 .145.021l.027.007a1 1 0 0 1 .462.262l5 5a1 1 0 1 1-1.414 1.414L13 5.414V15a1 1 0 1 1-2 0V5.414L7.707 8.707a1 1 0 1 1-1.414-1.414l5-5q.094-.093.208-.16l.044-.023a1 1 0 0 1 .197-.076l.05-.013.033-.005A1 1 0 0 1 11.98 2L12 2z"
    />
  </IconSvg>
);
export { Upload };
