// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import type { SVGProps } from "react";
const VideocamOffWarning = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    fill="none"
    viewBox="0 0 24 24"
    width={24}
    height={24}
    {...props}
  >
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M15.463 8.538Q16.926 10 19 10q2.075 0 3.538-1.463Q24 7.076 24 5t-1.462-3.537Q21.074 0 19 0q-2.075 0-3.537 1.463Q14 2.925 14 5t1.463 3.537M19.5 2v4h-1V2zm-.15 5.85a.48.48 0 0 1-.7 0 .48.48 0 0 1 0-.7.48.48 0 0 1 .7 0 .48.48 0 0 1 0 .7M19 12a6.9 6.9 0 0 1-3-.657v1.832l2 2V13.5l4 4v-6.157A6.9 6.9 0 0 1 19 12m-7-7q0 .51.066 1H8.825l-2-2h5.241Q12 4.49 12 5m8.55 18.35-3.591-3.59q-.43.24-.96.24H4q-.824 0-1.412-.587A1.93 1.93 0 0 1 2 18V6q0-.528.24-.96L.65 3.45l1.4-1.4L4 4l2 2 10 10 2 2 3.95 3.95zM4 6.8 15.2 18H4z"
      clipRule="evenodd"
    />
  </svg>
);
export { VideocamOffWarning };
