// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const VolumeDown = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M10.088 3.01c.25-.03.502-.005.741.074l.118.044.115.052c.224.113.42.274.576.472l.074.103.066.107c.145.255.221.544.222.838v14.597l-.005.126a1.71 1.71 0 0 1-1.047 1.451 1.71 1.71 0 0 1-1.86-.37l-3.384-3.386A.4.4 0 0 0 5.42 17H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h2.419a.4.4 0 0 0 .285-.118l3.387-3.386c.238-.238.542-.4.872-.466zM7.12 8.295a2.4 2.4 0 0 1-1.704.705L3 9v6h2.416a2.4 2.4 0 0 1 1.704.706l2.88 2.88V5.414z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      d="M15.4 8.2a1 1 0 0 1 1.4.2 6 6 0 0 1 0 7.2 1 1 0 0 1-1.6-1.2 4 4 0 0 0 0-4.8 1 1 0 0 1 .2-1.4"
    />
  </IconSvg>
);
export { VolumeDown };
