// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const WarningFilled = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M11.99 2.493a2.85 2.85 0 0 1 2.477 1.44l7.593 13.288.088.165a2.85 2.85 0 0 1-1.13 3.724c-.432.25-.923.383-1.422.383H4.406a2.85 2.85 0 0 1-2.478-1.413 2.85 2.85 0 0 1-.008-2.855L9.514 3.934a2.85 2.85 0 0 1 2.476-1.44M12 16a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2zm0-8a1 1 0 0 0-1 1v4a1 1 0 1 0 2 0V9a1 1 0 0 0-1-1"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { WarningFilled };
