// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const Warning = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M12.01 16a1 1 0 1 1 0 2H12a1 1 0 1 1 0-2zM12 8a1 1 0 0 1 1 1v4a1 1 0 1 1-2 0V9a1 1 0 0 1 1-1"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M11.99 1.986A3 3 0 0 1 14.6 3.504L22.597 17.5l.092.174a3.003 3.003 0 0 1-1.189 3.923 3 3 0 0 1-1.499.403H4a3 3 0 0 1-3.018-2.993 3 3 0 0 1 .4-1.503l8-14a3 3 0 0 1 2.608-1.518m0 2a1 1 0 0 0-.87.507v.003l-8 14-.004.004a1.002 1.002 0 0 0 .875 1.5H20a1 1 0 0 0 .865-.5 1 1 0 0 0 0-1l-.002-.004-8-14-.002-.003a1 1 0 0 0-.87-.507"
      clipRule="evenodd"
    />
  </IconSvg>
);
export { Warning };
