// Auto-generated by scripts/generate-icons.ts -- DO NOT EDIT
import { IconSvg, IconSvgProps } from ":/components/icon/IconSvg";
const WaveformOff = (props: IconSvgProps) => (
  <IconSvg {...props}>
    <path
      fill="currentColor"
      d="M4 11a1 1 0 1 1 0 2 1 1 0 0 1 0-2M8 11a1 1 0 1 1 0 2 1 1 0 0 1 0-2M12 11a1 1 0 1 1 0 2 1 1 0 0 1 0-2M16 11a1 1 0 1 1 0 2 1 1 0 0 1 0-2M20 11a1 1 0 1 1 0 2 1 1 0 0 1 0-2"
    />
  </IconSvg>
);
export { WaveformOff };
