name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  install-front:
    uses: ./.github/workflows/front-dependencies-installation.yml
    with:
      node_version: "20.x"

  lint-git:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' # Makes sense only for pull requests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: show
        run: git log
      - name: Enforce absence of print statements in code
        run: |
          ! git diff origin/${{ github.event.pull_request.base.ref }}..HEAD -- . ':(exclude)**/main.yml' | grep "print("
      - name: Check absence of fixup commits
        run: |
          ! git log | grep 'fixup!'
      - name: Install gitlint
        run: pip install --user requests gitlint
      - name: Lint commit messages added to main
        run: ~/.local/bin/gitlint --commits origin/${{ github.event.pull_request.base.ref }}..HEAD

  lint:
    runs-on: ubuntu-latest
    needs: install-front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Restore the frontend cache
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: front-node_modules-${{ hashFiles('yarn.lock') }}
          fail-on-cache-miss: true
      - name: Check linting
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: install-front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Restore the frontend cache
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: front-node_modules-${{ hashFiles('yarn.lock') }}
          fail-on-cache-miss: true
      - name: Run tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs: install-front
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Restore the frontend cache
        uses: actions/cache@v4
        with:
          path: "node_modules"
          key: front-node_modules-${{ hashFiles('yarn.lock') }}
          fail-on-cache-miss: true
      - name: Build
        run: yarn build
